# Cluster South Mumbai

#### In this analysis, the focus was South Mumbai, which is precisely area for foreign tourists. It is full of restaurants,hotelsand other places of entertainment.
### But upon complete analysis we noticed that most of the areas fall under single cluster. This can be due to Indian Restaurant.

#### Therefore, I decided to do a second iteration,by increasing number of clusters to 10 and see if clustering looks Okay.

Later a third iteration can be tried by discarding Indian restuarant and see how clusters change.

### A fourth iteration can be done with hybrid approach ie by discarding Indian Restaurant and increasing number of clusters at the same time.

#### A fifth iteration can be done by increasing number of areas from other parts of the city as well. It seems that entire South Mumbai by and large has similar charactersitics.

### Another question we may resolve is by comparing two different boroughs of Mumbai say South Mumbai and North Mumbai. How similar and how different they are.

**Library**

### So, Let's begin second iteration.

In [131]:
import pandas as pd
from pandas.io.json import json_normalize  # tranform JSON file into a pandas dataframe

import numpy as np

from bs4 import BeautifulSoup

# Matplotlib and associated plotting modules
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors

import seaborn as sns
from urllib.request import urlopen

import requests
# import k-means from clustering stage
from sklearn.cluster import KMeans

print("Library imported 61.")

Library imported 61.

In [132]:
import folium # map rendering library
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
print("Library imported 62.")

Library imported 62.

### **Let's Explore venues in South Mumbai **

In [133]:
areas = ["Colaba","Apollo Bandar","Fort","Churchgate","Nariman Point"
        ,"Marine Lines","Walkeshwar","Malabar Hill","Kalbadevi"
        ,"Bhuleshwar","Masjid Bandar","Darukhana","Pydhoni","Nagpada","Dongri","Byculla","Grand Road"
        ,"Mazgaon","Mumbai Central","Mahalaxmi","Worli"
]



full_address = []
 
for area in areas:
   
  full_address.append(area + ", Mumbai")

print("full_address",full_address)
print("areas",areas)

full_address ['Colaba, Mumbai', 'Apollo Bandar, Mumbai', 'Fort, Mumbai', 'Churchgate, Mumbai', 'Nariman Point, Mumbai', 'Marine Lines, Mumbai', 'Walkeshwar, Mumbai', 'Malabar Hill, Mumbai', 'Kalbadevi, Mumbai', 'Bhuleshwar, Mumbai', 'Masjid Bandar, Mumbai', 'Darukhana, Mumbai', 'Pydhoni, Mumbai', 'Nagpada, Mumbai', 'Dongri, Mumbai', 'Byculla, Mumbai', 'Grand Road, Mumbai', 'Mazgaon, Mumbai', 'Mumbai Central, Mumbai', 'Mahalaxmi, Mumbai', 'Worli, Mumbai']
areas ['Colaba', 'Apollo Bandar', 'Fort', 'Churchgate', 'Nariman Point', 'Marine Lines', 'Walkeshwar', 'Malabar Hill', 'Kalbadevi', 'Bhuleshwar', 'Masjid Bandar', 'Darukhana', 'Pydhoni', 'Nagpada', 'Dongri', 'Byculla', 'Grand Road', 'Mazgaon', 'Mumbai Central', 'Mahalaxmi', 'Worli']

In [134]:

dic1 = {"Neighborhood": areas,"Address":full_address}
dic1

{'Address': ['Colaba, Mumbai',
  'Apollo Bandar, Mumbai',
  'Fort, Mumbai',
  'Churchgate, Mumbai',
  'Nariman Point, Mumbai',
  'Marine Lines, Mumbai',
  'Walkeshwar, Mumbai',
  'Malabar Hill, Mumbai',
  'Kalbadevi, Mumbai',
  'Bhuleshwar, Mumbai',
  'Masjid Bandar, Mumbai',
  'Darukhana, Mumbai',
  'Pydhoni, Mumbai',
  'Nagpada, Mumbai',
  'Dongri, Mumbai',
  'Byculla, Mumbai',
  'Grand Road, Mumbai',
  'Mazgaon, Mumbai',
  'Mumbai Central, Mumbai',
  'Mahalaxmi, Mumbai',
  'Worli, Mumbai'],
 'Neighborhood': ['Colaba',
  'Apollo Bandar',
  'Fort',
  'Churchgate',
  'Nariman Point',
  'Marine Lines',
  'Walkeshwar',
  'Malabar Hill',
  'Kalbadevi',
  'Bhuleshwar',
  'Masjid Bandar',
  'Darukhana',
  'Pydhoni',
  'Nagpada',
  'Dongri',
  'Byculla',
  'Grand Road',
  'Mazgaon',
  'Mumbai Central',
  'Mahalaxmi',
  'Worli']}

In [135]:
df2 = pd.DataFrame.from_dict(dic1)
df2

      Neighborhood                 Address
0           Colaba          Colaba, Mumbai
1    Apollo Bandar   Apollo Bandar, Mumbai
2             Fort            Fort, Mumbai
3       Churchgate      Churchgate, Mumbai
4    Nariman Point   Nariman Point, Mumbai
5     Marine Lines    Marine Lines, Mumbai
6       Walkeshwar      Walkeshwar, Mumbai
7     Malabar Hill    Malabar Hill, Mumbai
8        Kalbadevi       Kalbadevi, Mumbai
9       Bhuleshwar      Bhuleshwar, Mumbai
10   Masjid Bandar   Masjid Bandar, Mumbai
11       Darukhana       Darukhana, Mumbai
12         Pydhoni         Pydhoni, Mumbai
13         Nagpada         Nagpada, Mumbai
14          Dongri          Dongri, Mumbai
15         Byculla         Byculla, Mumbai
16      Grand Road      Grand Road, Mumbai
17         Mazgaon         Mazgaon, Mumbai
18  Mumbai Central  Mumbai Central, Mumbai
19       Mahalaxmi       Mahalaxmi, Mumbai
20           Worli           Worli, Mumbai

In [137]:
## Note: This did not work in second iteration ?
borough = 'South Mumbai'
data = []
for  neighborhood,address in zip(df2['Neighborhood'], df2['Address']):
  print("neighborhood:", neighborhood)
  print("address:", address)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  print("latitude:", latitude)
  print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
neighborhoods.head()

neighborhood: Colaba
address: Colaba, Mumbai

GeocoderServiceError: ignored

In [138]:
neighborhoods.head()

    Neighborhood       Borough   Latitude  Longitude
0         Colaba  South Mumbai  18.915091  72.825969
1  Apollo Bandar  South Mumbai  18.918375  72.831443
2           Fort  South Mumbai  18.933266  72.834515
3     Churchgate  South Mumbai  18.935957  72.827340
4  Nariman Point  South Mumbai  18.925951  72.823208

In [109]:
neighborhoods.head(20)

      Neighborhood       Borough   Latitude  Longitude
0           Colaba  South Mumbai  18.915091  72.825969
1    Apollo Bandar  South Mumbai  18.918375  72.831443
2             Fort  South Mumbai  18.933266  72.834515
3       Churchgate  South Mumbai  18.935957  72.827340
4    Nariman Point  South Mumbai  18.925951  72.823208
5     Marine Lines  South Mumbai  18.945670  72.823781
6       Walkeshwar  South Mumbai  18.955343  72.807947
7     Malabar Hill  South Mumbai  18.958162  72.803366
8        Kalbadevi  South Mumbai  18.949258  72.827938
9       Bhuleshwar  South Mumbai  18.953771  72.827476
10   Masjid Bandar  South Mumbai  18.953599  72.838126
11       Darukhana  South Mumbai  18.977036  72.849077
12         Pydhoni  South Mumbai  18.953994  72.832379
13         Nagpada  South Mumbai  18.968178  72.828601
14          Dongri  South Mumbai  18.962226  72.836795
15         Byculla  South Mumbai  18.976622  72.832794
16      Grand Road  South Mumbai  18.938771  72.835335
17         Mazgaon  South Mumbai  18.968052  72.840012
18  Mumbai Central  South Mumbai  18.969586  72.819315
19       Mahalaxmi  South Mumbai  18.982568  72.824160

In [0]:
neighborhoods.to_csv("Mumbai_locations2.csv")

### Use geopy library to get the latitude and longitude values of New York City.
### In order to define an instance of the geocoder, we need to define a user_agent. We will name our agent ny_explorer, as shown below.

### Create a map of Mumbai with neighborhoods superimposed on top.

In [140]:
#South Mumbai : Latitude: 18.9600 Longitude: 72.8200
latitude = 18.9600
longitude = 72.8200
map_mumbai = folium.Map(location=[latitude, longitude], zoom_start=14)
map_mumbai

In [141]:

# add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_mumbai)  
    
map_mumbai

### Define Foursquare Credentials and Version

In [142]:
CLIENT_ID = 'AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC' # your Foursquare ID
CLIENT_SECRET = '5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC
CLIENT_SECRET:5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH

### Let's create a function to repeat the same process to all the neighborhoods in South Mumbai

In [0]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

### Now write the code to run the above function on each neighborhood and create a new dataframe called south_mumbai_venues.

In [144]:
south_mumbai_data = neighborhoods
print("dtypes:",south_mumbai_data.dtypes)
print("shape:",south_mumbai_data.shape)
south_mumbai_data.head(30)

dtypes: Neighborhood     object
Borough          object
Latitude        float64
Longitude       float64
dtype: object
shape: (21, 4)

      Neighborhood       Borough   Latitude  Longitude
0           Colaba  South Mumbai  18.915091  72.825969
1    Apollo Bandar  South Mumbai  18.918375  72.831443
2             Fort  South Mumbai  18.933266  72.834515
3       Churchgate  South Mumbai  18.935957  72.827340
4    Nariman Point  South Mumbai  18.925951  72.823208
5     Marine Lines  South Mumbai  18.945670  72.823781
6       Walkeshwar  South Mumbai  18.955343  72.807947
7     Malabar Hill  South Mumbai  18.958162  72.803366
8        Kalbadevi  South Mumbai  18.949258  72.827938
9       Bhuleshwar  South Mumbai  18.953771  72.827476
10   Masjid Bandar  South Mumbai  18.953599  72.838126
11       Darukhana  South Mumbai  18.977036  72.849077
12         Pydhoni  South Mumbai  18.953994  72.832379
13         Nagpada  South Mumbai  18.968178  72.828601
14          Dongri  South Mumbai  18.962226  72.836795
15         Byculla  South Mumbai  18.976622  72.832794
16      Grand Road  South Mumbai  18.938771  72.835335
17         Mazgaon  South Mumbai  18.968052  72.840012
18  Mumbai Central  South Mumbai  18.969586  72.819315
19       Mahalaxmi  South Mumbai  18.982568  72.824160
20           Worli  South Mumbai  19.011696  72.818070

#### Explore within a radius of 500 and limit number of nearby venues to 100.

In [0]:
radius= 500
LIMIT = 100

In [97]:
south_mumbai_venues = getNearbyVenues(names=south_mumbai_data['Neighborhood'],
                                   latitudes=south_mumbai_data['Latitude'],
                                   longitudes=south_mumbai_data['Longitude']
                                  )
print("dtypes:",south_mumbai_venues.dtypes)
print("shape:",south_mumbai_venues.shape)
south_mumbai_venues.head()

Colaba
Apollo Bandar
Fort
Churchgate
Nariman Point
Marine Lines
Walkeshwar
Malabar Hill
Kalbadevi
Bhuleshwar
Masjid Bandar
Darukhana
Pydhoni
Nagpada
Dongri
Byculla
Grand Road
Mazgaon
Mumbai Central
Mahalaxmi
Worli
dtypes: Neighborhood               object
Neighborhood Latitude     float64
Neighborhood Longitude    float64
Venue                      object
Venue Latitude            float64
Venue Longitude           float64
Venue Category             object
dtype: object
shape: (359, 7)

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.823843                Spa
3       Colaba              18.915091  ...        72.824160        Coffee Shop
4       Colaba              18.915091  ...        72.824119            Brewery

[5 rows x 7 columns]

### It returned total 359 venues.

####

In [98]:
# Ignore: Note: This template code for getting venues city by city.
radius= 500
LIMIT = 200
#Esenyurt 41.0413° N, 28.6941° E ===> 8
#Apollo Bandar	South Mumbai	18.9183748	72.8314429 ==> 46
#London 51.5074° N, -0.1278° W ==> 100
#New York 40.7128° N, 74.0060° W
#South Mumbai Latitude: 18.9600 Longitude: 72.8200 ===> Only 8 !!!!
#Istanbul 41.0082° N, 28.9784° E ==> 100
#29.3759° N, 47.9774° E

neighborhood_latitude = 29.3759
neighborhood_longitude = 47.9774

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url # display URL

# Send the GET request and examine the resutls

results = requests.get(url).json()
#results
#---------------------------------------------------------------
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#----------------------------------------------------------------
#Now we are ready to clean the json and structure it into a pandas dataframe.

venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

print("url:",url)
print("Total Nearby venues:",nearby_venues.shape[0])
nearby_venues.head()
#-----------------------------------------------------------------
nearby_venues_grouped = nearby_venues[['categories','lat']].groupby(['categories']).count().reset_index()
nearby_venues_grouped.rename(columns = {'lat':'count'},inplace = True)
nearby_venues_grouped_sorted = nearby_venues_grouped.sort_values(by= 'count',ascending=False)
print("Unique Categories:",nearby_venues_grouped_sorted.shape[0])
nearby_venues_grouped_sorted.head()

url: https://api.foursquare.com/v2/venues/explore?&client_id=AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC&client_secret=5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH&v=20180605&ll=29.3759,47.9774&radius=500&limit=200
Total Nearby venues: 46
Unique Categories: 19

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:46: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

                   categories  count
5                        Café     12
6                 Coffee Shop     10
3              Breakfast Spot      3
14  Middle Eastern Restaurant      3
4                Burger Joint      2

In [0]:
#res.reset_index().to_csv("thecsv.csv", orient='records', encoding="utf-8")
nearby_venues.to_csv("kuwait_venues2.csv",encoding="utf-8")
nearby_venues_grouped_sorted.to_csv("kuwait_unique_categories.csv",encoding="utf-8")

####

In [100]:
south_mumbai_venues.head()

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.823843                Spa
3       Colaba              18.915091  ...        72.824160        Coffee Shop
4       Colaba              18.915091  ...        72.824119            Brewery

[5 rows x 7 columns]

###

In [146]:
south_mumbai_venues.groupby('Neighborhood').count()

                Neighborhood Latitude  ...  Venue Category
Neighborhood                           ...
Apollo Bandar                      46  ...              46
Bhuleshwar                         11  ...              11
Byculla                            11  ...              11
Churchgate                         49  ...              49
Colaba                             13  ...              13
Darukhana                           5  ...               5
Dongri                              3  ...               3
Fort                               48  ...              48
Grand Road                         19  ...              19
Kalbadevi                           8  ...               8
Mahalaxmi                           7  ...               7
Malabar Hill                        7  ...               7
Marine Lines                       12  ...              12
Masjid Bandar                       8  ...               8
Mazgaon                             6  ...               6
Mumbai Central                     15  ...              15
Nagpada                            13  ...              13
Nariman Point                      32  ...              32
Pydhoni                            18  ...              18
Walkeshwar                         17  ...              17
Worli                              11  ...              11

[21 rows x 6 columns]

In [102]:
### Let's find out how many unique categories can be curated from all the returned venues

print('There are {} uniques categories.'.format(len(south_mumbai_venues['Venue Category'].unique())))

There are 104 uniques categories.

In [147]:
### 3. Analyze Each Neighborhood

# one hot encoding
south_mumbai_onehot = pd.get_dummies(south_mumbai_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
south_mumbai_onehot['Neighborhood'] = south_mumbai_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [south_mumbai_onehot.columns[-1]] + list(south_mumbai_onehot.columns[:-1])
south_mumbai_onehot = south_mumbai_onehot[fixed_columns]

south_mumbai_onehot.head()

  Neighborhood  Arcade  Asian Restaurant  ...  Wine Bar  Yoga Studio  Zoo
0       Colaba       0                 0  ...         0            0    0
1       Colaba       0                 0  ...         0            0    0
2       Colaba       0                 0  ...         0            0    0
3       Colaba       0                 0  ...         0            0    0
4       Colaba       0                 0  ...         0            0    0

[5 rows x 105 columns]

In [148]:
#And let's examine the new dataframe size.
south_mumbai_onehot.shape  # (359, 105)

(359, 105)

In [149]:
#Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

south_mumbai_grouped = south_mumbai_onehot.groupby('Neighborhood').mean().reset_index()
south_mumbai_grouped

      Neighborhood    Arcade  Asian Restaurant  ...  Wine Bar  Yoga Studio       Zoo
0    Apollo Bandar  0.000000          0.021739  ...   0.00000     0.000000  0.000000
1       Bhuleshwar  0.090909          0.000000  ...   0.00000     0.000000  0.000000
2          Byculla  0.000000          0.090909  ...   0.00000     0.000000  0.090909
3       Churchgate  0.000000          0.000000  ...   0.00000     0.000000  0.000000
4           Colaba  0.000000          0.000000  ...   0.00000     0.000000  0.000000
5        Darukhana  0.000000          0.000000  ...   0.00000     0.000000  0.000000
6           Dongri  0.000000          0.000000  ...   0.00000     0.000000  0.000000
7             Fort  0.000000          0.020833  ...   0.00000     0.000000  0.000000
8       Grand Road  0.000000          0.000000  ...   0.00000     0.000000  0.000000
9        Kalbadevi  0.000000          0.000000  ...   0.00000     0.000000  0.000000
10       Mahalaxmi  0.000000          0.000000  ...   0.00000     0.000000  0.000000
11    Malabar Hill  0.000000          0.000000  ...   0.00000     0.000000  0.000000
12    Marine Lines  0.000000          0.000000  ...   0.00000     0.000000  0.000000
13   Masjid Bandar  0.000000          0.000000  ...   0.00000     0.000000  0.000000
14         Mazgaon  0.000000          0.000000  ...   0.00000     0.000000  0.000000
15  Mumbai Central  0.000000          0.000000  ...   0.00000     0.000000  0.000000
16         Nagpada  0.000000          0.000000  ...   0.00000     0.000000  0.000000
17   Nariman Point  0.000000          0.000000  ...   0.03125     0.000000  0.000000
18         Pydhoni  0.055556          0.000000  ...   0.00000     0.000000  0.000000
19      Walkeshwar  0.000000          0.000000  ...   0.00000     0.000000  0.000000
20           Worli  0.000000          0.000000  ...   0.00000     0.090909  0.000000

[21 rows x 105 columns]

In [0]:
south_mumbai_grouped.to_csv("south_mumbai_grouped.csv")

In [150]:
south_mumbai_grouped.shape #(21, 105)

(21, 105)

In [151]:
## Let's print each neighborhood along with the top 5 most common venues

num_top_venues = 5

for hood in south_mumbai_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = south_mumbai_grouped[south_mumbai_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Apollo Bandar----
               venue  freq
0              Hotel  0.13
1  Indian Restaurant  0.11
2               Café  0.09
3        Coffee Shop  0.07
4                Bar  0.07


----Bhuleshwar----
                  venue  freq
0     Indian Restaurant  0.36
1                Arcade  0.09
2           Bus Station  0.09
3                  Food  0.09
4  Fast Food Restaurant  0.09


----Byculla----
               venue  freq
0  Indian Restaurant  0.18
1                Zoo  0.09
2                Bar  0.09
3         Restaurant  0.09
4           Pharmacy  0.09


----Churchgate----
                  venue  freq
0     Indian Restaurant  0.08
1        Ice Cream Shop  0.08
2        Cricket Ground  0.06
3  Fast Food Restaurant  0.06
4                 Hotel  0.06


----Colaba----
                venue  freq
0  Chinese Restaurant  0.15
1               Hotel  0.08
2                 Spa  0.08
3         Pizza Place  0.08
4          Restaurant  0.08


----Darukhana----
              venue  freq
0   Harbor / Marina   0.2
1     Train Station   0.2
2             Train   0.2
3  Community Center   0.2
4       Flea Market   0.2


----Dongri----
                       venue  freq
0          Indian Restaurant  0.67
1                Fish Market  0.33
2                     Arcade  0.00
3  Middle Eastern Restaurant  0.00
4      Outdoors & Recreation  0.00


----Fort----
                  venue  freq
0     Indian Restaurant  0.19
1          Dessert Shop  0.06
2    Seafood Restaurant  0.06
3                  Café  0.04
4  Fast Food Restaurant  0.04


----Grand Road----
                venue  freq
0   Indian Restaurant  0.21
1          Irani Cafe  0.11
2                 Bar  0.11
3  Chinese Restaurant  0.05
4         Coffee Shop  0.05


----Kalbadevi----
                  venue  freq
0     Indian Restaurant  0.38
1                  Café  0.12
2  Fast Food Restaurant  0.12
3                Market  0.12
4           Cheese Shop  0.12


----Mahalaxmi----
                  venue  freq
0     Indian Restaurant  0.14
1                   Gym  0.14
2             Nightclub  0.14
3           Coffee Shop  0.14
4  Fast Food Restaurant  0.14


----Malabar Hill----
                  venue  freq
0                  Park  0.29
1                Bakery  0.14
2                  Bank  0.14
3                   Gym  0.14
4  Fast Food Restaurant  0.14


----Marine Lines----
                   venue  freq
0      Indian Restaurant  0.17
1                    Gym  0.08
2  Outdoors & Recreation  0.08
3         Scenic Lookout  0.08
4     Chinese Restaurant  0.08


----Masjid Bandar----
                venue  freq
0   Indian Restaurant  0.38
1   Convenience Store  0.12
2      Sandwich Place  0.12
3  Chinese Restaurant  0.12
4          Smoke Shop  0.12


----Mazgaon----
               venue  freq
0     Ice Cream Shop  0.17
1  Indian Restaurant  0.17
2               Café  0.17
3              Train  0.17
4        Snack Place  0.17


----Mumbai Central----
                  venue  freq
0      Department Store  0.13
1     Indian Restaurant  0.13
2  Fast Food Restaurant  0.13
3         Bowling Alley  0.07
4                 Diner  0.07


----Nagpada----
                       venue  freq
0          Indian Restaurant  0.15
1  Middle Eastern Restaurant  0.08
2               Cupcake Shop  0.08
3       Fast Food Restaurant  0.08
4                Pizza Place  0.08


----Nariman Point----
                venue  freq
0  Italian Restaurant  0.09
1   Indian Restaurant  0.09
2             Theater  0.09
3         Chaat Place  0.06
4               Hotel  0.06


----Pydhoni----
               venue  freq
0  Indian Restaurant  0.44
1             Arcade  0.06
2               Café  0.06
3  Indian Sweet Shop  0.06
4          Juice Bar  0.06


----Walkeshwar----
               venue  freq
0  Indian Restaurant  0.29
1         Restaurant  0.12
2     Ice Cream Shop  0.06
3          Gastropub  0.06
4               Park  0.06


----Worli----
            venue  freq
0  Scenic Lookout  0.27
1           Hotel  0.09
2       Gun Range  0.09
3       Juice Bar  0.09
4     Sports Club  0.09

In [0]:
#Let's put that into a pandas dataframe
#First, let's write a function to sort the venues in descending orde

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [153]:
#Now let's create the new dataframe and display the top 10 venues for each neighborhood.

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = south_mumbai_grouped['Neighborhood']

for ind in np.arange(south_mumbai_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(south_mumbai_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

    Neighborhood  ... 10th Most Common Venue
0  Apollo Bandar  ...             Restaurant
1     Bhuleshwar  ...           Cupcake Shop
2        Byculla  ...         History Museum
3     Churchgate  ...     Chinese Restaurant
4         Colaba  ...                  Hotel

[5 rows x 11 columns]

In [154]:
neighborhoods_venues_sorted.head()

    Neighborhood  ... 10th Most Common Venue
0  Apollo Bandar  ...             Restaurant
1     Bhuleshwar  ...           Cupcake Shop
2        Byculla  ...         History Museum
3     Churchgate  ...     Chinese Restaurant
4         Colaba  ...                  Hotel

[5 rows x 11 columns]

In [0]:
neighborhoods_venues_sorted.to_csv("south_mumbai_top10_venue_categories.csv")

# The second iteration starts from here.

## Increase number of clusters from 5 to 10.

In [155]:
# 4. Cluster Neighborhoods

# Run k-means to cluster the neighborhood into 5 clusters.
# Try with more clusters and see results.

# set number of clusters
#kclusters = 5 # First Iteration
kclusters = 10 # Second Iteration

south_mumbai_grouped_clustering = south_mumbai_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(south_mumbai_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 1, 0, 0, 0, 3, 2, 0, 0, 1], dtype=int32)

In [0]:
#Ignore : Test Code
#neighborhoods_venues_sorted_xx = neighborhoods_venues_sorted
#neighborhoods_venues_sorted_xx.head()
#neighborhoods_venues_sorted_xx.insert(0, 'Cluster Labels', kmeans.labels_)
#neighborhoods_venues_sorted_xx.head()
#neighborhoods_venues_sorted_xx.to_csv("south_mumbai_clustered.csv")

In [122]:
#south_mumbai_data.head()

    Neighborhood       Borough   Latitude  Longitude
0         Colaba  South Mumbai  18.915091  72.825969
1  Apollo Bandar  South Mumbai  18.918375  72.831443
2           Fort  South Mumbai  18.933266  72.834515
3     Churchgate  South Mumbai  18.935957  72.827340
4  Nariman Point  South Mumbai  18.925951  72.823208

In [156]:
### Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

south_mumbai_merged = south_mumbai_data


# merge two dataframes
south_mumbai_merged = south_mumbai_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

south_mumbai_merged.head() 
# check 'Cluster Labels' column has been added to dataframe

    Neighborhood  ... 10th Most Common Venue
0         Colaba  ...                  Hotel
1  Apollo Bandar  ...             Restaurant
2           Fort  ...       Parsi Restaurant
3     Churchgate  ...     Chinese Restaurant
4  Nariman Point  ...            Coffee Shop

[5 rows x 15 columns]

In [0]:
south_mumbai_merged.to_csv("south_mumbai_cluster_iteration_2.csv")

In [130]:
#Finally, let's visualize the resulting clusters
#South Mumbai Latitude: 18.9600 Longitude: 72.8200
latitude  = 18.9600
longitude = 72.8200

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(south_mumbai_merged['Latitude'], south_mumbai_merged['Longitude'], south_mumbai_merged['Neighborhood'], south_mumbai_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters