# **Cluster South Mumbai**

# **Iteration # : 6**

## **Add new boroughs**

#### In this analysis, the focus was South Mumbai, which is precisely area for foreign tourists. It is full of restaurants,hotelsand other places of entertainment.
### But upon complete analysis we noticed that most of the areas fall under single cluster. This can be due to Indian Restaurant.

#### Therefore, I decided to do a second iteration,by increasing number of clusters to 10 and see if clustering looks Okay.

Later a third iteration can be tried by discarding Indian restuarant and see how clusters change.

### A fourth iteration can be done with hybrid approach ie by discarding Indian Restaurant and increasing number of clusters at the same time.

#### A sixth iteration can be done by increasing number of areas from other parts of the city as well. It seems that entire South Mumbai by and large has similar charactersitics.

### A fifth iteration can be done by increasing radius to 900 m.

### Seventh iteration : Another question we may resolve is by comparing two different boroughs of Mumbai say South Mumbai and North Mumbai. How similar and how different they are.

#### By increasing radius, lot of overlappring of nearby neighborhood happened, and many duplicate venues appeared. These duplicates can be eliminated.

**Library**

### So, Let's begin second iteration.

In [3]:
import pandas as pd
from pandas.io.json import json_normalize  # tranform JSON file into a pandas dataframe

import numpy as np

from bs4 import BeautifulSoup

# Matplotlib and associated plotting modules
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors

import seaborn as sns
from urllib.request import urlopen

import requests
# import k-means from clustering stage
from sklearn.cluster import KMeans

print("Library imported 71.")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Library imported 71.

In [4]:
import folium # map rendering library
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
print("Library imported 72.")

Library imported 72.

In [0]:
areas_south = ["Colaba","Apollo Bandar","Fort","Churchgate","Nariman Point" \
        ,"Marine Lines","Walkeshwar","Malabar Hill","Kalbadevi","Bhuleshwar" \
        ,"Masjid Bandar","Darukhana","Pydhoni","Nagpada","Dongri" \
        ,"Byculla","Grand Road","Mazgaon","Mumbai Central","Mahalaxmi" \
        ,"Worli"]
#areas_south

In [0]:
areas_west = ["Dadar","Bandra West","Juhu","Aksa Beach","Andheri" \
              "Kalina","Santa Cruz","Mahim","Khar"]
        
#areas_west

In [90]:
areas_east = ["Kurla","Ghatkopar","Chembur","Govandi","Mulund West"] 
areas_east

['Kurla', 'Ghatkopar', 'Chembur', 'Govandi', 'Mulund West']

In [92]:
areas_north = ["Powai","Jogeshwari","Malad","Borivali","Mira Road"] 
areas_north

['Powai', 'Jogeshwari', 'Malad', 'Borivali', 'Mira Road']

In [0]:
areas2 = ["Colaba","Apollo Bandar","Fort","Churchgate","Nariman Point"
        ,"Marine Lines","Walkeshwar","Malabar Hill","Kalbadevi"
        ,"Bhuleshwar","Masjid Bandar","Darukhana","Pydhoni","Nagpada","Dongri","Byculla","Grand Road"
        ,"Mazgaon","Mumbai Central","Mahalaxmi","Worli"
]
areas3 = ["Ghatkopar"]
areas4 = ["Chembur"]
areas5 = areas3 + areas4

In [105]:
boroughs_south_mumbai = ["South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai"]
#boroughs_south_mumbai  
len(boroughs_south_mumbai)

21

In [0]:
boroughs_west_mumbai = ["West Mumbai","West Mumbai","West Mumbai","West Mumbai","West Mumbai", \
             "West Mumbai","West Mumbai","West Mumbai","West Mumbai"]
             
            
#boroughs_west_mumbai

In [81]:
boroughs_east_mumbai = ["East Mumbai","East Mumbai","East Mumbai","East Mumbai","East Mumbai"]
boroughs_east_mumbai

['East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai']

In [82]:
boroughs_north_mumbai = ["North Mumbai","North Mumbai","North Mumbai","North Mumbai","North Mumbai"]
boroughs_north_mumbai

['North Mumbai',
 'North Mumbai',
 'North Mumbai',
 'North Mumbai',
 'North Mumbai']

In [0]:
#boroughs = boroughs_south_mumbai + boroughs_west_mumbai + boroughs_east_mumbai + boroughs_north_mumbai
#boroughs
boroughs1 =  boroughs_south_mumbai
boroughs2 =  boroughs_west_mumbai + boroughs_east_mumbai + boroughs_north_mumbai

In [0]:
#areas = areas_south + areas_west + areas_east + areas_north
areas1 = areas_south
areas2 = areas_west + areas_east + areas_north

#areas

In [0]:
full_address1 = []
 
for area in areas1:
   
  full_address1.append(area + ", Mumbai")

In [0]:
full_address2 = []
 
for area in areas2:
   
  full_address2.append(area + ", Mumbai")

In [127]:
print("Lenght of areas1={} , boroughs1 = {} , full_address1 = {}" \
.format(len(areas1),len(boroughs1),len(full_address1)))

print("Lenght of areas2={} , boroughs2 = {} , full_address2 = {}" \
.format(len(areas2),len(boroughs2),len(full_address2)))

Lenght of areas1=21 , boroughs1 = 21 , full_address1 = 21
Lenght of areas2=19 , boroughs2 = 19 , full_address2 = 19

In [128]:
#dic_test1 = {"Neighborhood": areas,"Boroughs": boroughs,"Address":full_address}
dic_area1 = {"Neighborhood": areas1,"Boroughs": boroughs1,"Address":full_address1}
dic_area2 = {"Neighborhood": areas2,"Boroughs": boroughs2,"Address":full_address2}
print("dic_area1:",dic_area1)
print("dic_area2:",dic_area2)

dic_area1: {'Neighborhood': ['Colaba', 'Apollo Bandar', 'Fort', 'Churchgate', 'Nariman Point', 'Marine Lines', 'Walkeshwar', 'Malabar Hill', 'Kalbadevi', 'Bhuleshwar', 'Masjid Bandar', 'Darukhana', 'Pydhoni', 'Nagpada', 'Dongri', 'Byculla', 'Grand Road', 'Mazgaon', 'Mumbai Central', 'Mahalaxmi', 'Worli'], 'Boroughs': ['South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai'], 'Address': ['Colaba, Mumbai', 'Apollo Bandar, Mumbai', 'Fort, Mumbai', 'Churchgate, Mumbai', 'Nariman Point, Mumbai', 'Marine Lines, Mumbai', 'Walkeshwar, Mumbai', 'Malabar Hill, Mumbai', 'Kalbadevi, Mumbai', 'Bhuleshwar, Mumbai', 'Masjid Bandar, Mumbai', 'Darukhana, Mumbai', 'Pydhoni, Mumbai', 'Nagpada, Mumbai', 'Dongri, Mumbai', 'Byculla, Mumbai', 'Grand Road, Mumbai', 'Mazgaon, Mumbai', 'Mumbai Central, Mumbai', 'Mahalaxmi, Mumbai', 'Worli, Mumbai']}
dic_area2: {'Neighborhood': ['Dadar', 'Bandra West', 'Juhu', 'Aksa Beach', 'Andheri', 'Kalina', 'Santa Cruz', 'Mahim', 'Khar', 'Kurla', 'Ghatkopar', 'Chembur', 'Govandi', 'Mulund West', 'Powai', 'Jogeshwari', 'Malad', 'Borivali', 'Mira Road'], 'Boroughs': ['West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'North Mumbai', 'North Mumbai', 'North Mumbai', 'North Mumbai', 'North Mumbai'], 'Address': ['Dadar, Mumbai', 'Bandra West, Mumbai', 'Juhu, Mumbai', 'Aksa Beach, Mumbai', 'Andheri, Mumbai', 'Kalina, Mumbai', 'Santa Cruz, Mumbai', 'Mahim, Mumbai', 'Khar, Mumbai', 'Kurla, Mumbai', 'Ghatkopar, Mumbai', 'Chembur, Mumbai', 'Govandi, Mumbai', 'Mulund West, Mumbai', 'Powai, Mumbai', 'Jogeshwari, Mumbai', 'Malad, Mumbai', 'Borivali, Mumbai', 'Mira Road, Mumbai']}

In [129]:
df_area1 = pd.DataFrame.from_dict(dic_area1)
df_area1.head()
#df_area1.to_csv("mumbai_south_neighborhood_all.csv")

    Neighborhood      Boroughs                Address
0         Colaba  South Mumbai         Colaba, Mumbai
1  Apollo Bandar  South Mumbai  Apollo Bandar, Mumbai
2           Fort  South Mumbai           Fort, Mumbai
3     Churchgate  South Mumbai     Churchgate, Mumbai
4  Nariman Point  South Mumbai  Nariman Point, Mumbai

In [131]:
df_area2 = pd.DataFrame.from_dict(dic_area2)
df_area2.tail()
#df_area2.to_csv("mumbai_south_neighborhood_all.csv")

   Neighborhood      Boroughs             Address
14        Powai  North Mumbai       Powai, Mumbai
15   Jogeshwari  North Mumbai  Jogeshwari, Mumbai
16        Malad  North Mumbai       Malad, Mumbai
17     Borivali  North Mumbai    Borivali, Mumbai
18    Mira Road  North Mumbai   Mira Road, Mumbai

In [0]:
areas = areas1

### **Let's Explore venues in South Mumbai **

In [7]:

full_address = []
 
for area in areas:
   
  full_address.append(area + ", Mumbai")

print("full_address",full_address)
print("areas",areas)

full_address ['Colaba, Mumbai', 'Apollo Bandar, Mumbai', 'Fort, Mumbai', 'Churchgate, Mumbai', 'Nariman Point, Mumbai', 'Marine Lines, Mumbai', 'Walkeshwar, Mumbai', 'Malabar Hill, Mumbai', 'Kalbadevi, Mumbai', 'Bhuleshwar, Mumbai', 'Masjid Bandar, Mumbai', 'Darukhana, Mumbai', 'Pydhoni, Mumbai', 'Nagpada, Mumbai', 'Dongri, Mumbai', 'Byculla, Mumbai', 'Grand Road, Mumbai', 'Mazgaon, Mumbai', 'Mumbai Central, Mumbai', 'Mahalaxmi, Mumbai', 'Worli, Mumbai']
areas ['Colaba', 'Apollo Bandar', 'Fort', 'Churchgate', 'Nariman Point', 'Marine Lines', 'Walkeshwar', 'Malabar Hill', 'Kalbadevi', 'Bhuleshwar', 'Masjid Bandar', 'Darukhana', 'Pydhoni', 'Nagpada', 'Dongri', 'Byculla', 'Grand Road', 'Mazgaon', 'Mumbai Central', 'Mahalaxmi', 'Worli']

In [8]:

dic1 = {"Neighborhood": areas,"Address":full_address}
dic1

{'Address': ['Colaba, Mumbai',
  'Apollo Bandar, Mumbai',
  'Fort, Mumbai',
  'Churchgate, Mumbai',
  'Nariman Point, Mumbai',
  'Marine Lines, Mumbai',
  'Walkeshwar, Mumbai',
  'Malabar Hill, Mumbai',
  'Kalbadevi, Mumbai',
  'Bhuleshwar, Mumbai',
  'Masjid Bandar, Mumbai',
  'Darukhana, Mumbai',
  'Pydhoni, Mumbai',
  'Nagpada, Mumbai',
  'Dongri, Mumbai',
  'Byculla, Mumbai',
  'Grand Road, Mumbai',
  'Mazgaon, Mumbai',
  'Mumbai Central, Mumbai',
  'Mahalaxmi, Mumbai',
  'Worli, Mumbai'],
 'Neighborhood': ['Colaba',
  'Apollo Bandar',
  'Fort',
  'Churchgate',
  'Nariman Point',
  'Marine Lines',
  'Walkeshwar',
  'Malabar Hill',
  'Kalbadevi',
  'Bhuleshwar',
  'Masjid Bandar',
  'Darukhana',
  'Pydhoni',
  'Nagpada',
  'Dongri',
  'Byculla',
  'Grand Road',
  'Mazgaon',
  'Mumbai Central',
  'Mahalaxmi',
  'Worli']}

In [9]:
df2 = pd.DataFrame.from_dict(dic1)
df2

      Neighborhood                 Address
0           Colaba          Colaba, Mumbai
1    Apollo Bandar   Apollo Bandar, Mumbai
2             Fort            Fort, Mumbai
3       Churchgate      Churchgate, Mumbai
4    Nariman Point   Nariman Point, Mumbai
5     Marine Lines    Marine Lines, Mumbai
6       Walkeshwar      Walkeshwar, Mumbai
7     Malabar Hill    Malabar Hill, Mumbai
8        Kalbadevi       Kalbadevi, Mumbai
9       Bhuleshwar      Bhuleshwar, Mumbai
10   Masjid Bandar   Masjid Bandar, Mumbai
11       Darukhana       Darukhana, Mumbai
12         Pydhoni         Pydhoni, Mumbai
13         Nagpada         Nagpada, Mumbai
14          Dongri          Dongri, Mumbai
15         Byculla         Byculla, Mumbai
16      Grand Road      Grand Road, Mumbai
17         Mazgaon         Mazgaon, Mumbai
18  Mumbai Central  Mumbai Central, Mumbai
19       Mahalaxmi       Mahalaxmi, Mumbai
20           Worli           Worli, Mumbai

In [119]:
df2 = df_test1
df2.shape
df2.tail()

   Neighborhood      Boroughs             Address
35        Powai  North Mumbai       Powai, Mumbai
36   Jogeshwari  North Mumbai  Jogeshwari, Mumbai
37        Malad  North Mumbai       Malad, Mumbai
38     Borivali  North Mumbai    Borivali, Mumbai
39    Mira Road  North Mumbai   Mira Road, Mumbai

In [0]:
#df_area1
#df_area2

### **Let's pass south Mumbai df_area1**

In [133]:
df2 = df_area1
df2.shape

(21, 3)

In [134]:
data = []
for  neighborhood,address in zip(df2['Neighborhood'], df2['Address']):
  print("neighborhood:", neighborhood)
  print("address:", address)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  print("latitude:", latitude)
  print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
#neighborhoods.head()

neighborhood: Colaba
address: Colaba, Mumbai
latitude: 18.915091
longitude: 72.8259691
neighborhood: Apollo Bandar
address: Apollo Bandar, Mumbai
latitude: 18.9183748
longitude: 72.8314429
neighborhood: Fort
address: Fort, Mumbai
latitude: 18.9332665
longitude: 72.8345146
neighborhood: Churchgate
address: Churchgate, Mumbai
latitude: 18.9359567
longitude: 72.8273404
neighborhood: Nariman Point
address: Nariman Point, Mumbai
latitude: 18.9259514
longitude: 72.8232083
neighborhood: Marine Lines
address: Marine Lines, Mumbai
latitude: 18.9456701
longitude: 72.823781
neighborhood: Walkeshwar
address: Walkeshwar, Mumbai
latitude: 18.9553434
longitude: 72.8079469
neighborhood: Malabar Hill
address: Malabar Hill, Mumbai
latitude: 18.9581616
longitude: 72.8033665
neighborhood: Kalbadevi
address: Kalbadevi, Mumbai
latitude: 18.9492575
longitude: 72.8279382
neighborhood: Bhuleshwar
address: Bhuleshwar, Mumbai
latitude: 18.9537706
longitude: 72.8274755
neighborhood: Masjid Bandar
address: Masjid Bandar, Mumbai
latitude: 18.953598550000002
longitude: 72.8381264997544
neighborhood: Darukhana
address: Darukhana, Mumbai
latitude: 18.9770363
longitude: 72.8490768
neighborhood: Pydhoni
address: Pydhoni, Mumbai
latitude: 18.9539939
longitude: 72.8323786
neighborhood: Nagpada
address: Nagpada, Mumbai
latitude: 18.9681782
longitude: 72.8286009
neighborhood: Dongri
address: Dongri, Mumbai
latitude: 18.9622265
longitude: 72.836795
neighborhood: Byculla
address: Byculla, Mumbai
latitude: 18.9766219
longitude: 72.8327936
neighborhood: Grand Road
address: Grand Road, Mumbai
latitude: 18.9387711
longitude: 72.8353355
neighborhood: Mazgaon
address: Mazgaon, Mumbai
latitude: 18.9680519
longitude: 72.84001187036267
neighborhood: Mumbai Central
address: Mumbai Central, Mumbai
latitude: 18.9695855
longitude: 72.8193152
neighborhood: Mahalaxmi
address: Mahalaxmi, Mumbai
latitude: 18.9825679
longitude: 72.82416
neighborhood: Worli
address: Worli, Mumbai
latitude: 19.0116962
longitude: 72.8180702
dtypes :  Neighborhood     object
Borough          object
Latitude        float64
Longitude       float64
dtype: object
rows :  21

In [0]:
neighborhoods1 = neighborhoods
neighborhoods1.head()
neighborhoods1.to_csv("south_mumbai_latitudes.csv")

### **Now let's pass east+west+north Mumabi df_area2**

In [137]:
df2 = df_area2
df2.shape

(19, 3)

In [138]:
data = []
for  neighborhood,address in zip(df2['Neighborhood'], df2['Address']):
  print("neighborhood:", neighborhood)
  print("address:", address)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  print("latitude:", latitude)
  print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
#neighborhoods.head()

neighborhood: Dadar
address: Dadar, Mumbai
latitude: 19.019282
longitude: 72.8428757
neighborhood: Bandra West
address: Bandra West, Mumbai
latitude: 19.0583358
longitude: 72.8302669
neighborhood: Juhu
address: Juhu, Mumbai
latitude: 19.1070215
longitude: 72.8275275
neighborhood: Aksa Beach
address: Aksa Beach, Mumbai
latitude: 19.1853321
longitude: 72.79634888359624
neighborhood: Andheri
address: Andheri, Mumbai
latitude: 19.1196976
longitude: 72.8464205
neighborhood: Kalina
address: Kalina, Mumbai
latitude: 19.079273
longitude: 72.8612672
neighborhood: Santa Cruz
address: Santa Cruz, Mumbai
latitude: 19.0793694
longitude: 72.8470855
neighborhood: Mahim
address: Mahim, Mumbai
latitude: 19.0423145
longitude: 72.8398344
neighborhood: Khar
address: Khar, Mumbai
latitude: 19.0696584
longitude: 72.8398944
neighborhood: Kurla
address: Kurla, Mumbai
latitude: 19.0652797
longitude: 72.8793805
neighborhood: Ghatkopar
address: Ghatkopar, Mumbai
latitude: 19.0859539
longitude: 72.9082381
neighborhood: Chembur
address: Chembur, Mumbai
latitude: 19.0612128
longitude: 72.8975909
neighborhood: Govandi
address: Govandi, Mumbai
latitude: 19.0553688
longitude: 72.9150702
neighborhood: Mulund West
address: Mulund West, Mumbai
latitude: 19.1719717
longitude: 72.9511956
neighborhood: Powai
address: Powai, Mumbai
latitude: 19.1187195
longitude: 72.9073476
neighborhood: Jogeshwari
address: Jogeshwari, Mumbai
latitude: 19.1348994
longitude: 72.8488199
neighborhood: Malad
address: Malad, Mumbai
latitude: 19.1867193
longitude: 72.8485884
neighborhood: Borivali
address: Borivali, Mumbai
latitude: 19.229068
longitude: 72.8573628
neighborhood: Mira Road
address: Mira Road, Mumbai
latitude: 19.1878962
longitude: 72.8365955
dtypes :  Neighborhood     object
Borough          object
Latitude        float64
Longitude       float64
dtype: object
rows :  19

In [141]:
neighborhoods2 = neighborhoods
neighborhoods2.shape # (19, 4)
neighborhoods2.head()
neighborhoods2.tail()

   Neighborhood       Borough   Latitude  Longitude
14        Powai  South Mumbai  19.118720  72.907348
15   Jogeshwari  South Mumbai  19.134899  72.848820
16        Malad  South Mumbai  19.186719  72.848588
17     Borivali  South Mumbai  19.229068  72.857363
18    Mira Road  South Mumbai  19.187896  72.836596

In [121]:
## Note: This did not work in second iteration ?
## Note: But, in next iteration it worked !!!!
#borough = 'South Mumbai'
data = []
for  neighborhood,address in zip(df2['Neighborhood'], df2['Address']):
  print("neighborhood:", neighborhood)
  print("address:", address)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  print("latitude:", latitude)
  print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
neighborhoods.head()

neighborhood: Colaba
address: Colaba, Mumbai
latitude: 18.915091
longitude: 72.8259691
neighborhood: Apollo Bandar
address: Apollo Bandar, Mumbai
latitude: 18.9183748
longitude: 72.8314429
neighborhood: Fort
address: Fort, Mumbai
latitude: 18.9332665
longitude: 72.8345146
neighborhood: Churchgate
address: Churchgate, Mumbai
latitude: 18.9359567
longitude: 72.8273404
neighborhood: Nariman Point
address: Nariman Point, Mumbai
latitude: 18.9259514
longitude: 72.8232083
neighborhood: Marine Lines
address: Marine Lines, Mumbai
latitude: 18.9456701
longitude: 72.823781
neighborhood: Walkeshwar
address: Walkeshwar, Mumbai
latitude: 18.9553434
longitude: 72.8079469
neighborhood: Malabar Hill
address: Malabar Hill, Mumbai
latitude: 18.9581616
longitude: 72.8033665
neighborhood: Kalbadevi
address: Kalbadevi, Mumbai
latitude: 18.9492575
longitude: 72.8279382
neighborhood: Bhuleshwar
address: Bhuleshwar, Mumbai
latitude: 18.9537706
longitude: 72.8274755
neighborhood: Masjid Bandar
address: Masjid Bandar, Mumbai
latitude: 18.953598550000002
longitude: 72.8381264997544
neighborhood: Darukhana
address: Darukhana, Mumbai
latitude: 18.9770363
longitude: 72.8490768
neighborhood: Pydhoni
address: Pydhoni, Mumbai
latitude: 18.9539939
longitude: 72.8323786
neighborhood: Nagpada
address: Nagpada, Mumbai
latitude: 18.9681782
longitude: 72.8286009
neighborhood: Dongri
address: Dongri, Mumbai
latitude: 18.9622265
longitude: 72.836795
neighborhood: Byculla
address: Byculla, Mumbai
latitude: 18.9766219
longitude: 72.8327936
neighborhood: Grand Road
address: Grand Road, Mumbai
latitude: 18.9387711
longitude: 72.8353355
neighborhood: Mazgaon
address: Mazgaon, Mumbai
latitude: 18.9680519
longitude: 72.84001187036267
neighborhood: Mumbai Central
address: Mumbai Central, Mumbai
latitude: 18.9695855
longitude: 72.8193152
neighborhood: Mahalaxmi
address: Mahalaxmi, Mumbai
latitude: 18.9825679
longitude: 72.82416
neighborhood: Worli
address: Worli, Mumbai
latitude: 19.0116962
longitude: 72.8180702
neighborhood: Dadar
address: Dadar, Mumbai
latitude: 19.019282
longitude: 72.8428757
neighborhood: Bandra West
address: Bandra West, Mumbai
latitude: 19.0583358
longitude: 72.8302669
neighborhood: Juhu
address: Juhu, Mumbai
latitude: 19.1070215
longitude: 72.8275275
neighborhood: Aksa Beach
address: Aksa Beach, Mumbai
latitude: 19.1853321
longitude: 72.79634888359624
neighborhood: Andheri
address: Andheri, Mumbai
latitude: 19.1196976
longitude: 72.8464205
neighborhood: Kalina
address: Kalina, Mumbai
latitude: 19.079273
longitude: 72.8612672
neighborhood: Santa Cruz
address: Santa Cruz, Mumbai
latitude: 19.0793694
longitude: 72.8470855
neighborhood: Mahim
address: Mahim, Mumbai
latitude: 19.0423145
longitude: 72.8398344
neighborhood: Khar
address: Khar, Mumbai
latitude: 19.0696584
longitude: 72.8398944
neighborhood: Kurla
address: Kurla, Mumbai
latitude: 19.0652797
longitude: 72.8793805
neighborhood: Ghatkopar
address: Ghatkopar, Mumbai
latitude: 19.0859539
longitude: 72.9082381
neighborhood: Chembur
address: Chembur, Mumbai
latitude: 19.0612128
longitude: 72.8975909
neighborhood: Govandi
address: Govandi, Mumbai
latitude: 19.0553688
longitude: 72.9150702
neighborhood: Mulund West
address: Mulund West, Mumbai
latitude: 19.1719717
longitude: 72.9511956
neighborhood: Powai
address: Powai, Mumbai
latitude: 19.1187195
longitude: 72.9073476
neighborhood: Jogeshwari
address: Jogeshwari, Mumbai

GeocoderServiceError: ignored

## **Now Let's concat two dataframes**

In [161]:
neighborhoods = neighborhoods1.append(neighborhoods2,ignore_index=True)
neighborhoods.shape
#neighborhoods.head(40)
#result = df1.append(df2)
#bigdata = data1.append(data2, ignore_index=True)

      Neighborhood       Borough   Latitude  Longitude
0           Colaba  South Mumbai  18.915091  72.825969
1    Apollo Bandar  South Mumbai  18.918375  72.831443
2             Fort  South Mumbai  18.933266  72.834515
3       Churchgate  South Mumbai  18.935957  72.827340
4    Nariman Point  South Mumbai  18.925951  72.823208
5     Marine Lines  South Mumbai  18.945670  72.823781
6       Walkeshwar  South Mumbai  18.955343  72.807947
7     Malabar Hill  South Mumbai  18.958162  72.803366
8        Kalbadevi  South Mumbai  18.949258  72.827938
9       Bhuleshwar  South Mumbai  18.953771  72.827476
10   Masjid Bandar  South Mumbai  18.953599  72.838126
11       Darukhana  South Mumbai  18.977036  72.849077
12         Pydhoni  South Mumbai  18.953994  72.832379
13         Nagpada  South Mumbai  18.968178  72.828601
14          Dongri  South Mumbai  18.962226  72.836795
15         Byculla  South Mumbai  18.976622  72.832794
16      Grand Road  South Mumbai  18.938771  72.835335
17         Mazgaon  South Mumbai  18.968052  72.840012
18  Mumbai Central  South Mumbai  18.969586  72.819315
19       Mahalaxmi  South Mumbai  18.982568  72.824160
20           Worli  South Mumbai  19.011696  72.818070
21           Dadar  South Mumbai  19.019282  72.842876
22     Bandra West  South Mumbai  19.058336  72.830267
23            Juhu  South Mumbai  19.107021  72.827528
24      Aksa Beach  South Mumbai  19.185332  72.796349
25         Andheri  South Mumbai  19.119698  72.846420
26          Kalina  South Mumbai  19.079273  72.861267
27      Santa Cruz  South Mumbai  19.079369  72.847086
28           Mahim  South Mumbai  19.042314  72.839834
29            Khar  South Mumbai  19.069658  72.839894
30           Kurla  South Mumbai  19.065280  72.879380
31       Ghatkopar  South Mumbai  19.085954  72.908238
32         Chembur  South Mumbai  19.061213  72.897591
33         Govandi  South Mumbai  19.055369  72.915070
34     Mulund West  South Mumbai  19.171972  72.951196
35           Powai  South Mumbai  19.118720  72.907348
36      Jogeshwari  South Mumbai  19.134899  72.848820
37           Malad  South Mumbai  19.186719  72.848588
38        Borivali  South Mumbai  19.229068  72.857363
39       Mira Road  South Mumbai  19.187896  72.836596

In [0]:
neighborhoods = neighborhoods.reset_index()

In [163]:
print("Merged data frame have rows.", neighborhoods.shape[0])
neighborhoods.head()
neighborhoods.tail()
neighborhoods.to_csv("all_mumbai_latitude.csv")
neighborhoods.tail()

Merged data frame have rows. 40

   Neighborhood       Borough   Latitude  Longitude
35        Powai  South Mumbai  19.118720  72.907348
36   Jogeshwari  South Mumbai  19.134899  72.848820
37        Malad  South Mumbai  19.186719  72.848588
38     Borivali  South Mumbai  19.229068  72.857363
39    Mira Road  South Mumbai  19.187896  72.836596

In [0]:
neighborhoods.to_csv("Mumbai_locations2.csv")

### Use geopy library to get the latitude and longitude values of New York City.
### In order to define an instance of the geocoder, we need to define a user_agent. We will name our agent ny_explorer, as shown below.

### Create a map of Mumbai with neighborhoods superimposed on top.

In [164]:
#South Mumbai : Latitude: 18.9600 Longitude: 72.8200
latitude = 18.9600
longitude = 72.8200
map_mumbai = folium.Map(location=[latitude, longitude], zoom_start=14)
map_mumbai

In [165]:

# add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_mumbai)  
    
map_mumbai

### Define Foursquare Credentials and Version

In [166]:
CLIENT_ID = 'AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC' # your Foursquare ID
CLIENT_SECRET = '5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC
CLIENT_SECRET:5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH

### Let's create a function to repeat the same process to all the neighborhoods in South Mumbai

# Fifth Iteration with a radius = 900

In [22]:
radius=900
LIMIT = 100
print("The radius is = {} and LIMIT is = {}".format(radius,LIMIT))

The radius is = 900 and LIMIT is = 100

In [0]:
def getNearbyVenues(names, latitudes, longitudes, radius=650):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

### Now write the code to run the above function on each neighborhood and create a new dataframe called south_mumbai_venues.

In [0]:
south_mumbai_data = neighborhoods
#print("dtypes:",south_mumbai_data.dtypes)
#print("shape:",south_mumbai_data.shape)
#south_mumbai_data.head()

### Adjust radius here.

In [0]:
radius = 900

In [169]:
south_mumbai_venues = getNearbyVenues(names=south_mumbai_data['Neighborhood'],
                                   latitudes=south_mumbai_data['Latitude'],
                                   longitudes=south_mumbai_data['Longitude']
                                   
                                  )
print("dtypes:",south_mumbai_venues.dtypes)
print("Total venues retrieved:",south_mumbai_venues.shape[0])

south_mumbai_venues.head()

Colaba
Apollo Bandar
Fort
Churchgate
Nariman Point
Marine Lines
Walkeshwar
Malabar Hill
Kalbadevi
Bhuleshwar
Masjid Bandar
Darukhana
Pydhoni
Nagpada
Dongri
Byculla
Grand Road
Mazgaon
Mumbai Central
Mahalaxmi
Worli
Dadar
Bandra West
Juhu
Aksa Beach
Andheri
Kalina
Santa Cruz
Mahim
Khar
Kurla
Ghatkopar
Chembur
Govandi
Mulund West
Powai
Jogeshwari
Malad
Borivali
Mira Road
dtypes: Neighborhood               object
Neighborhood Latitude     float64
Neighborhood Longitude    float64
Venue                      object
Venue Latitude            float64
Venue Longitude           float64
Venue Category             object
dtype: object
Total venues retrieved: 1126

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.821080    Thai Restaurant
3       Colaba              18.915091  ...        72.829185       Dessert Shop
4       Colaba              18.915091  ...        72.821028              Hotel

[5 rows x 7 columns]

#**IGNORE : Test Code**

In [0]:
south_mumbai_venues.to_csv("all_mumbai_venues.csv")

In [171]:
duplicate1 = south_mumbai_venues
print("How many rows before dropping duplicates={}".format(duplicate1.shape[0]))
duplicate1 = duplicate1.drop_duplicates(subset=['Venue Latitude', 'Venue Longitude'])
print("How many rows after dropping duplicates={}".format(duplicate1.shape[0]))
#duplicate1.to_csv("south_mumbai_venues_no_duplicates.csv")
south_mumbai_venues.to_csv("all_mumbai_venues_650.csv")

How many rows before dropping duplicates=1126
How many rows after dropping duplicates=1010

### It returned total 359 venues.
### Venues increased to 873 with a radius of 900.

# **Duplicates Issue**

### Are there any duplicates due to overlapping of areas.

# **Third Iteration**

### Remove rows with Indian Restaurants.

In [172]:
#Backup dataframe
south_mumbai_venues_bkp = south_mumbai_venues
south_mumbai_indian_restaurants = south_mumbai_venues[(south_mumbai_venues['Venue Category'] == "Indian Restaurant")]
print("south_mumbai_indian_restaurants:",south_mumbai_indian_restaurants.shape[0])  #62
south_mumbai_indian_restaurants.head()
south_mumbai_indian_restaurants.to_csv("south_mumbai_indian_restaurants.csv")

#indian_restaurants: 140

south_mumbai_indian_restaurants: 166

In [173]:
#south_mumbai_venues.dtypes
print("south_mumbai_venues:rows:bef:",south_mumbai_venues.shape[0])
south_mumbai_venues = south_mumbai_venues[(south_mumbai_venues['Venue Category'] != "Indian Restaurant")].reset_index()
print("south_mumbai_venues:rows:aft:",south_mumbai_venues.shape[0])
south_mumbai_venues.to_csv("south_mumbai_minus_indian_restaurants.csv")
south_mumbai_venues.head()
#353 to 292
#873 to 733

south_mumbai_venues:rows:bef: 1126
south_mumbai_venues:rows:aft: 960

   index Neighborhood  ...  Venue Longitude     Venue Category
0      0       Colaba  ...        72.824151        Men's Store
1      1       Colaba  ...        72.827018  German Restaurant
2      2       Colaba  ...        72.821080    Thai Restaurant
3      3       Colaba  ...        72.829185       Dessert Shop
4      4       Colaba  ...        72.821028              Hotel

[5 rows x 8 columns]

# **IGNORE**

In [98]:
# Ignore: Note: This template code for getting venues city by city.
radius= 500
LIMIT = 200
#Esenyurt 41.0413° N, 28.6941° E ===> 8
#Apollo Bandar	South Mumbai	18.9183748	72.8314429 ==> 46
#London 51.5074° N, -0.1278° W ==> 100
#New York 40.7128° N, 74.0060° W
#South Mumbai Latitude: 18.9600 Longitude: 72.8200 ===> Only 8 !!!!
#Istanbul 41.0082° N, 28.9784° E ==> 100
#29.3759° N, 47.9774° E

neighborhood_latitude = 29.3759
neighborhood_longitude = 47.9774

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url # display URL

# Send the GET request and examine the resutls

results = requests.get(url).json()
#results
#---------------------------------------------------------------
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#----------------------------------------------------------------
#Now we are ready to clean the json and structure it into a pandas dataframe.

venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

print("url:",url)
print("Total Nearby venues:",nearby_venues.shape[0])
nearby_venues.head()
#-----------------------------------------------------------------
nearby_venues_grouped = nearby_venues[['categories','lat']].groupby(['categories']).count().reset_index()
nearby_venues_grouped.rename(columns = {'lat':'count'},inplace = True)
nearby_venues_grouped_sorted = nearby_venues_grouped.sort_values(by= 'count',ascending=False)
print("Unique Categories:",nearby_venues_grouped_sorted.shape[0])
nearby_venues_grouped_sorted.head()

url: https://api.foursquare.com/v2/venues/explore?&client_id=AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC&client_secret=5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH&v=20180605&ll=29.3759,47.9774&radius=500&limit=200
Total Nearby venues: 46
Unique Categories: 19

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:46: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

                   categories  count
5                        Café     12
6                 Coffee Shop     10
3              Breakfast Spot      3
14  Middle Eastern Restaurant      3
4                Burger Joint      2

In [0]:
#res.reset_index().to_csv("thecsv.csv", orient='records', encoding="utf-8")
nearby_venues.to_csv("kuwait_venues2.csv",encoding="utf-8")
nearby_venues_grouped_sorted.to_csv("kuwait_unique_categories.csv",encoding="utf-8")

####

In [100]:
south_mumbai_venues.head()

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.823843                Spa
3       Colaba              18.915091  ...        72.824160        Coffee Shop
4       Colaba              18.915091  ...        72.824119            Brewery

[5 rows x 7 columns]

# **Start Again**

In [0]:
south_mumbai_venues_x1 = south_mumbai_venues.groupby('Neighborhood').count()
south_mumbai_venues_x1.to_csv("all_mumbai_venues_x1_groupby.csv")

In [176]:
### Let's find out how many unique categories can be curated from all the returned venues

print('There are {} uniques categories.'.format(len(south_mumbai_venues['Venue Category'].unique())))
# 104 to 103 to 102  
#120 radius = 90

There are 158 uniques categories.

In [177]:
### 3. Analyze Each Neighborhood

# one hot encoding
south_mumbai_onehot = pd.get_dummies(south_mumbai_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
south_mumbai_onehot['Neighborhood'] = south_mumbai_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [south_mumbai_onehot.columns[-1]] + list(south_mumbai_onehot.columns[:-1])
south_mumbai_onehot = south_mumbai_onehot[fixed_columns]

south_mumbai_onehot.head()

  Neighborhood  Accessories Store  ...  Yoga Studio  Zoo
0       Colaba                  0  ...            0    0
1       Colaba                  0  ...            0    0
2       Colaba                  0  ...            0    0
3       Colaba                  0  ...            0    0
4       Colaba                  0  ...            0    0

[5 rows x 159 columns]

In [178]:
#And let's examine the new dataframe size.
south_mumbai_onehot.shape  # (359, 105) (292,103)

(960, 159)

In [179]:
#Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

south_mumbai_grouped = south_mumbai_onehot.groupby('Neighborhood').mean().reset_index()
south_mumbai_grouped

      Neighborhood  Accessories Store  ...  Yoga Studio       Zoo
0          Andheri           0.000000  ...       0.0000  0.000000
1    Apollo Bandar           0.000000  ...       0.0000  0.000000
2      Bandra West           0.000000  ...       0.0000  0.000000
3       Bhuleshwar           0.000000  ...       0.0000  0.000000
4         Borivali           0.000000  ...       0.0000  0.000000
5          Byculla           0.000000  ...       0.0000  0.142857
6          Chembur           0.000000  ...       0.0000  0.000000
7       Churchgate           0.000000  ...       0.0000  0.000000
8           Colaba           0.000000  ...       0.0000  0.000000
9            Dadar           0.000000  ...       0.0000  0.000000
10       Darukhana           0.000000  ...       0.0000  0.000000
11          Dongri           0.000000  ...       0.0000  0.000000
12            Fort           0.000000  ...       0.0000  0.000000
13       Ghatkopar           0.052632  ...       0.0000  0.000000
14         Govandi           0.000000  ...       0.0000  0.000000
15      Grand Road           0.000000  ...       0.0000  0.000000
16      Jogeshwari           0.000000  ...       0.0000  0.000000
17            Juhu           0.000000  ...       0.0000  0.000000
18       Kalbadevi           0.000000  ...       0.0000  0.000000
19          Kalina           0.000000  ...       0.0000  0.000000
20            Khar           0.000000  ...       0.0000  0.000000
21           Kurla           0.000000  ...       0.0000  0.000000
22       Mahalaxmi           0.000000  ...       0.0000  0.000000
23           Mahim           0.000000  ...       0.0000  0.000000
24    Malabar Hill           0.000000  ...       0.0000  0.000000
25           Malad           0.000000  ...       0.0000  0.000000
26    Marine Lines           0.000000  ...       0.0000  0.000000
27   Masjid Bandar           0.000000  ...       0.0000  0.000000
28         Mazgaon           0.000000  ...       0.0000  0.000000
29       Mira Road           0.000000  ...       0.0000  0.000000
30     Mulund West           0.000000  ...       0.0000  0.000000
31  Mumbai Central           0.000000  ...       0.0000  0.000000
32         Nagpada           0.000000  ...       0.0000  0.000000
33   Nariman Point           0.000000  ...       0.0000  0.000000
34           Powai           0.000000  ...       0.0000  0.000000
35         Pydhoni           0.000000  ...       0.0000  0.000000
36      Santa Cruz           0.000000  ...       0.0000  0.000000
37      Walkeshwar           0.000000  ...       0.0000  0.000000
38           Worli           0.000000  ...       0.0625  0.000000

[39 rows x 159 columns]

In [0]:
south_mumbai_grouped.to_csv("south_mumbai_grouped.csv")

In [46]:
south_mumbai_grouped.shape #(21, 105)->(21,103)

(21, 121)

In [180]:
## Let's print each neighborhood along with the top 5 most common venues

num_top_venues = 5

for hood in south_mumbai_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = south_mumbai_grouped[south_mumbai_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Andheri----
                  venue  freq
0  Fast Food Restaurant  0.20
1            Restaurant  0.07
2            Food Court  0.07
3                  Café  0.07
4         Shopping Mall  0.07


----Apollo Bandar----
         venue  freq
0        Hotel  0.11
1         Café  0.08
2          Bar  0.08
3  Coffee Shop  0.05
4        Diner  0.05


----Bandra West----
                venue  freq
0                Café  0.10
1              Bakery  0.07
2                 Bar  0.07
3    Asian Restaurant  0.05
4  Chinese Restaurant  0.05


----Bhuleshwar----
                  venue  freq
0        Ice Cream Shop  0.13
1           Snack Place  0.13
2     Indian Sweet Shop  0.07
3                Bakery  0.07
4  Fast Food Restaurant  0.07


----Borivali----
                           venue  freq
0                 Ice Cream Shop  0.12
1             Chinese Restaurant  0.08
2  Vegetarian / Vegan Restaurant  0.08
3                 Clothing Store  0.08
4                      Juice Bar  0.08


----Byculla----
              venue  freq
0            Bakery  0.29
1               Zoo  0.14
2  Asian Restaurant  0.14
3               Bar  0.14
4       Pizza Place  0.14


----Chembur----
                           venue  freq
0             Seafood Restaurant  0.14
1                         Garden  0.10
2  Vegetarian / Vegan Restaurant  0.10
3                            Bar  0.10
4                           Café  0.10


----Churchgate----
                  venue  freq
0  Fast Food Restaurant  0.08
1        Ice Cream Shop  0.07
2                 Hotel  0.07
3        Cricket Ground  0.07
4           Coffee Shop  0.05


----Colaba----
         venue  freq
0  Coffee Shop  0.12
1   Restaurant  0.09
2        Diner  0.06
3  Pizza Place  0.06
4        Hotel  0.06


----Dadar----
                           venue  freq
0           Fast Food Restaurant  0.15
1                    Coffee Shop  0.11
2                 Breakfast Spot  0.07
3  Vegetarian / Vegan Restaurant  0.07
4                  Movie Theater  0.07


----Darukhana----
               venue  freq
0        Flea Market  0.33
1               Café  0.33
2         Restaurant  0.33
3  Accessories Store  0.00
4        Music Venue  0.00


----Dongri----
               venue  freq
0              Hotel  0.25
1       Dessert Shop  0.25
2         Restaurant  0.25
3        Music Venue  0.25
4  Accessories Store  0.00


----Fort----
                  venue  freq
0                  Café  0.09
1    Seafood Restaurant  0.06
2    Chinese Restaurant  0.06
3          Dessert Shop  0.05
4  Fast Food Restaurant  0.05


----Ghatkopar----
                  venue  freq
0             Juice Bar  0.11
1           Pizza Place  0.11
2     Accessories Store  0.05
3       Bed & Breakfast  0.05
4  Gym / Fitness Center  0.05


----Govandi----
               venue  freq
0           Platform  0.25
1               Park  0.25
2  Food & Drink Shop  0.25
3         Food Truck  0.25
4   Parsi Restaurant  0.00


----Grand Road----
                venue  freq
0                Café  0.12
1  Seafood Restaurant  0.12
2               Hotel  0.08
3          Irani Cafe  0.08
4  Chinese Restaurant  0.08


----Jogeshwari----
                venue  freq
0  Mughlai Restaurant   0.4
1         Pizza Place   0.2
2    Asian Restaurant   0.2
3  Chinese Restaurant   0.2
4           Nightclub   0.0


----Juhu----
                venue  freq
0                 Bar  0.09
1               Hotel  0.07
2  Chinese Restaurant  0.07
3                Café  0.07
4                 Spa  0.04


----Kalbadevi----
                  venue  freq
0                  Café  0.17
1  Fast Food Restaurant  0.17
2                   Bar  0.08
3        Ice Cream Shop  0.08
4   American Restaurant  0.08


----Kalina----
                venue  freq
0  Chinese Restaurant  0.22
1        Burger Joint  0.11
2      Ice Cream Shop  0.11
3         Snack Place  0.11
4    Asian Restaurant  0.11


----Khar----
                  venue  freq
0                   Bar  0.10
1  Fast Food Restaurant  0.06
2                Lounge  0.06
3                   Pub  0.06
4    Bengali Restaurant  0.03


----Kurla----
                           venue  freq
0  Vegetarian / Vegan Restaurant  0.25
1            Arts & Crafts Store  0.25
2                  Train Station  0.25
3                     Shoe Store  0.25
4              Accessories Store  0.00


----Mahalaxmi----
                      venue  freq
0               Coffee Shop  0.22
1                 Nightclub  0.11
2                 Racetrack  0.11
3  Mediterranean Restaurant  0.11
4          Asian Restaurant  0.11


----Mahim----
                  venue  freq
0        Breakfast Spot  0.11
1         Train Station  0.11
2          Dessert Shop  0.11
3            Restaurant  0.11
4  Fast Food Restaurant  0.11


----Malabar Hill----
                  venue  freq
0          Dessert Shop  0.18
1                  Park  0.18
2                Bakery  0.09
3  Fast Food Restaurant  0.09
4           Snack Place  0.09


----Malad----
                  venue  freq
0  Fast Food Restaurant  0.38
1         Metro Station  0.12
2           Snack Place  0.12
3     Mobile Phone Shop  0.12
4          Dessert Shop  0.12


----Marine Lines----
                venue  freq
0          Food Truck  0.10
1              Bakery  0.10
2                Café  0.10
3  Chinese Restaurant  0.05
4           Multiplex  0.05


----Masjid Bandar----
               venue  freq
0    Harbor / Marina  0.24
1         Restaurant  0.12
2  Convenience Store  0.12
3         Smoke Shop  0.06
4               Café  0.06


----Mazgaon----
                  venue  freq
0    Chinese Restaurant  0.17
1  Fast Food Restaurant  0.08
2           Flea Market  0.08
3          Dessert Shop  0.08
4        Ice Cream Shop  0.08


----Mira Road----
                  venue  freq
0                   Pub  0.07
1        Clothing Store  0.07
2  Fast Food Restaurant  0.07
3                   Bar  0.05
4                  Café  0.05


----Mulund West----
                  venue  freq
0  Fast Food Restaurant  0.20
1          Dessert Shop  0.10
2                  Pool  0.05
3               Theater  0.05
4           Men's Store  0.05


----Mumbai Central----
                  venue  freq
0  Fast Food Restaurant  0.20
1      Department Store  0.15
2        Ice Cream Shop  0.10
3    Chinese Restaurant  0.10
4            Restaurant  0.05


----Nagpada----
                  venue  freq
0  Fast Food Restaurant  0.15
1    Chinese Restaurant  0.15
2      Department Store  0.10
3          Cupcake Shop  0.05
4                Bakery  0.05


----Nariman Point----
                  venue  freq
0    Italian Restaurant  0.09
1                 Hotel  0.07
2  Fast Food Restaurant  0.07
3               Theater  0.07
4            Restaurant  0.07


----Powai----
                venue  freq
0      Ice Cream Shop  0.05
1          Restaurant  0.05
2         Coffee Shop  0.05
3  Chinese Restaurant  0.05
4              Bakery  0.05


----Pydhoni----
                venue  freq
0        Dessert Shop  0.08
1           Juice Bar  0.08
2                Café  0.08
3                Food  0.08
4  Chinese Restaurant  0.08


----Santa Cruz----
                       venue  freq
0                      Hotel  0.12
1                     Bakery  0.06
2  Middle Eastern Restaurant  0.06
3                 Food Court  0.06
4         Chinese Restaurant  0.06


----Walkeshwar----
                  venue  freq
0            Restaurant  0.08
1        Ice Cream Shop  0.08
2  Fast Food Restaurant  0.08
3     Food & Drink Shop  0.04
4            Food Truck  0.04


----Worli----
            venue  freq
0            Café  0.19
1  Scenic Lookout  0.19
2          Bakery  0.06
3     Sports Club  0.06
4     Coffee Shop  0.06

In [0]:
#Let's put that into a pandas dataframe
#First, let's write a function to sort the venues in descending orde

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [182]:
#Now let's create the new dataframe and display the top 10 venues for each neighborhood.

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = south_mumbai_grouped['Neighborhood']

for ind in np.arange(south_mumbai_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(south_mumbai_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

    Neighborhood  ... 10th Most Common Venue
0        Andheri  ...             Restaurant
1  Apollo Bandar  ...    Japanese Restaurant
2    Bandra West  ...            Coffee Shop
3     Bhuleshwar  ...      Indian Sweet Shop
4       Borivali  ...                   Café

[5 rows x 11 columns]

In [0]:
neighborhoods_venues_sorted.to_csv("south_mumbai_top10_venue_categories_minus_indian_rest.csv")

# The second iteration starts from here.

## Increase number of clusters from 5 to 10.

In [0]:
# Run k-means to cluster the neighborhood into 5 clusters.
# Try with more clusters and see results.
# set number of clusters
#kclusters = 5 # First Iteration
#kclusters = 10 # Second Iteration
#kclusters = 5 # Third Iteration after removing Indian restaurants
kclusters = 10 # Fourth Iteration after removing Indian restaurants

In [184]:
# 4. Cluster Neighborhoods
south_mumbai_grouped_clustering = south_mumbai_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(south_mumbai_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 4, 4, 4, 0, 9, 4, 0, 4, 0], dtype=int32)

In [189]:
### Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

ValueError: ignored

In [190]:
neighborhoods_venues_sorted.dtypes

Cluster Labels             int32
Neighborhood              object
1st Most Common Venue     object
2nd Most Common Venue     object
3rd Most Common Venue     object
4th Most Common Venue     object
5th Most Common Venue     object
6th Most Common Venue     object
7th Most Common Venue     object
8th Most Common Venue     object
9th Most Common Venue     object
10th Most Common Venue    object
dtype: object

In [186]:
### Now merge both dataframes

south_mumbai_merged = south_mumbai_data

# merge two dataframes
south_mumbai_merged = south_mumbai_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

south_mumbai_merged.head() 
# check 'Cluster Labels' column has been added to dataframe

    Neighborhood       Borough  ...  9th Most Common Venue  10th Most Common Venue
0         Colaba  South Mumbai  ...                Brewery             Men's Store
1  Apollo Bandar  South Mumbai  ...             Restaurant     Japanese Restaurant
2           Fort  South Mumbai  ...         Clothing Store                  Lounge
3     Churchgate  South Mumbai  ...          Train Station               Bookstore
4  Nariman Point  South Mumbai  ...                   Café                   Diner

[5 rows x 15 columns]

In [193]:
# Find rows where cluster is missing
df_missing_cluster = south_mumbai_merged[south_mumbai_merged["Cluster Labels"]].notna()
df_missing_cluster.head()
#df = df[df['EPS'].notna()]

KeyError: ignored

In [197]:
#df.dropna(subset = ['column1_name', 'column2_name', 'column3_name'])
print("rows bef:",south_mumbai_merged.shape[0])
south_mumbai_merged.dropna()
print("rows aft:",south_mumbai_merged.shape[0])

rows bef: 40
rows aft: 40

In [198]:
print("rows bef:",south_mumbai_merged.shape[0])
south_mumbai_merged = south_mumbai_merged[(south_mumbai_merged.Neighborhood != "Aksa Beach")]
print("rows aft:",south_mumbai_merged.shape[0])

#df = df[(df.risk == "Small") | (df.risk == "Medium") | (df.risk == "High")]

rows bef: 40
rows aft: 39

In [199]:
south_mumbai_merged.dtypes #Cluster Labels float64
south_mumbai_merged[["Cluster Labels"]] = south_mumbai_merged[["Cluster Labels"]].astype(int)
south_mumbai_merged.dtypes

Neighborhood               object
Borough                    object
Latitude                  float64
Longitude                 float64
Cluster Labels              int64
1st Most Common Venue      object
2nd Most Common Venue      object
3rd Most Common Venue      object
4th Most Common Venue      object
5th Most Common Venue      object
6th Most Common Venue      object
7th Most Common Venue      object
8th Most Common Venue      object
9th Most Common Venue      object
10th Most Common Venue     object
dtype: object

In [0]:
south_mumbai_merged.to_csv("all_mumbai_cluster_k10_r650.csv")

In [200]:
#Finally, let's visualize the resulting clusters
#South Mumbai Latitude: 18.9600 Longitude: 72.8200
latitude  = 18.9600
longitude = 72.8200

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(south_mumbai_merged['Latitude'], south_mumbai_merged['Longitude'], south_mumbai_merged['Neighborhood'], south_mumbai_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

### This concludes the iteration No . Thank You.