# **Cluster South Mumbai**

# **Iteration # : 7**

# **Version 9**

# **Two key changes in approach**
## Decided to give weight to categories based on their importance to 
## visitors and rarity.
## Similar Categories merged.
## Wrong categories corrected.

## Version 8 : for all Mumbai : Removed aksa. 
## Fixed Issue : borough all coming as South Mumbai
## Requires code cleanup : Done.

## **Add new boroughs**

#### In this analysis, the focus was South Mumbai, which is precisely area for foreign tourists. It is full of restaurants,hotelsand other places of entertainment.
### But upon complete analysis we noticed that most of the areas fall under single cluster. This can be due to Indian Restaurant.

#### Therefore, I decided to do a second iteration,by increasing number of clusters to 10 and see if clustering looks Okay.

Later a third iteration can be tried by discarding Indian restuarant and see how clusters change.

### A fourth iteration can be done with hybrid approach ie by discarding Indian Restaurant and increasing number of clusters at the same time.

#### A sixth iteration can be done by increasing number of areas from other parts of the city as well. It seems that entire South Mumbai by and large has similar charactersitics.

### A fifth iteration can be done by increasing radius to 900 m.

### Seventh iteration : Another question we may resolve is by comparing two different boroughs of Mumbai say South Mumbai and North Mumbai. How similar and how different they are.

#### By increasing radius, lot of overlappring of nearby neighborhood happened, and many duplicate venues appeared. These duplicates can be eliminated.

**Library**

### So, Let's begin second iteration.

In [2]:
import pandas as pd
from pandas.io.json import json_normalize  # tranform JSON file into a pandas dataframe

import numpy as np

from bs4 import BeautifulSoup

# Matplotlib and associated plotting modules
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors

import seaborn as sns
from urllib.request import urlopen

import requests
# import k-means from clustering stage
from sklearn.cluster import KMeans

print("Library imported 111.")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Library imported 111.

In [3]:
import folium # map rendering library
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
print("Library imported 112.")

Library imported 112.

In [0]:
areas_south = ["Colaba","Apollo Bandar","Fort","Churchgate","Nariman Point" \
        ,"Marine Lines","Walkeshwar","Malabar Hill","Kalbadevi","Bhuleshwar" \
        ,"Masjid Bandar","Darukhana","Pydhoni","Nagpada","Dongri" \
        ,"Byculla","Grand Road","Mazgaon","Mumbai Central","Mahalaxmi" \
        ,"Worli"]
#areas_south

In [0]:
areas_west = ["Dadar","Bandra West","Juhu","Andheri","Kalina" \
              ,"Santa Cruz","Mahim","Khar"]
        
#areas_west

In [6]:
areas_east = ["Kurla","Ghatkopar","Chembur","Govandi","Mulund West"] 
areas_east

['Kurla', 'Ghatkopar', 'Chembur', 'Govandi', 'Mulund West']

In [7]:
areas_north = ["Powai","Jogeshwari","Malad","Borivali","Mira Road"] 
areas_north

['Powai', 'Jogeshwari', 'Malad', 'Borivali', 'Mira Road']

In [8]:
boroughs_south_mumbai = ["South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai"]
#boroughs_south_mumbai  
len(boroughs_south_mumbai)

21

In [0]:
boroughs_west_mumbai = ["West Mumbai","West Mumbai","West Mumbai","West Mumbai","West Mumbai" \
             ,"West Mumbai","West Mumbai","West Mumbai"]
             
            
#boroughs_west_mumbai

In [10]:
boroughs_east_mumbai = ["East Mumbai","East Mumbai","East Mumbai","East Mumbai","East Mumbai"]
boroughs_east_mumbai

['East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai']

In [11]:
boroughs_north_mumbai = ["North Mumbai","North Mumbai","North Mumbai","North Mumbai","North Mumbai"]
boroughs_north_mumbai

['North Mumbai',
 'North Mumbai',
 'North Mumbai',
 'North Mumbai',
 'North Mumbai']

In [0]:
#boroughs = boroughs_south_mumbai + boroughs_west_mumbai + boroughs_east_mumbai + boroughs_north_mumbai
#boroughs
boroughs1 =  boroughs_south_mumbai
boroughs2 =  boroughs_west_mumbai + boroughs_east_mumbai + boroughs_north_mumbai

In [0]:
#areas = areas_south + areas_west + areas_east + areas_north
areas1 = areas_south
areas2 = areas_west + areas_east + areas_north

#areas

In [0]:
full_address1 = []
 
for area in areas1:
   
  full_address1.append(area + ", Mumbai")

In [0]:
full_address2 = []
 
for area in areas2:
   
  full_address2.append(area + ", Mumbai")

In [16]:
print("Lenght of areas1={} , boroughs1 = {} , full_address1 = {}" \
.format(len(areas1),len(boroughs1),len(full_address1)))

print("Lenght of areas2={} , boroughs2 = {} , full_address2 = {}" \
.format(len(areas2),len(boroughs2),len(full_address2)))

Lenght of areas1=21 , boroughs1 = 21 , full_address1 = 21
Lenght of areas2=18 , boroughs2 = 18 , full_address2 = 18

In [17]:
#dic_test1 = {"Neighborhood": areas,"Boroughs": boroughs,"Address":full_address}
dic_area1 = {"Neighborhood": areas1,"Boroughs": boroughs1,"Address":full_address1}
dic_area2 = {"Neighborhood": areas2,"Boroughs": boroughs2,"Address":full_address2}
print("dic_area1:",dic_area1)
print("dic_area2:",dic_area2)

dic_area1: {'Neighborhood': ['Colaba', 'Apollo Bandar', 'Fort', 'Churchgate', 'Nariman Point', 'Marine Lines', 'Walkeshwar', 'Malabar Hill', 'Kalbadevi', 'Bhuleshwar', 'Masjid Bandar', 'Darukhana', 'Pydhoni', 'Nagpada', 'Dongri', 'Byculla', 'Grand Road', 'Mazgaon', 'Mumbai Central', 'Mahalaxmi', 'Worli'], 'Boroughs': ['South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai', 'South Mumbai'], 'Address': ['Colaba, Mumbai', 'Apollo Bandar, Mumbai', 'Fort, Mumbai', 'Churchgate, Mumbai', 'Nariman Point, Mumbai', 'Marine Lines, Mumbai', 'Walkeshwar, Mumbai', 'Malabar Hill, Mumbai', 'Kalbadevi, Mumbai', 'Bhuleshwar, Mumbai', 'Masjid Bandar, Mumbai', 'Darukhana, Mumbai', 'Pydhoni, Mumbai', 'Nagpada, Mumbai', 'Dongri, Mumbai', 'Byculla, Mumbai', 'Grand Road, Mumbai', 'Mazgaon, Mumbai', 'Mumbai Central, Mumbai', 'Mahalaxmi, Mumbai', 'Worli, Mumbai']}
dic_area2: {'Neighborhood': ['Dadar', 'Bandra West', 'Juhu', 'Andheri', 'Kalina', 'Santa Cruz', 'Mahim', 'Khar', 'Kurla', 'Ghatkopar', 'Chembur', 'Govandi', 'Mulund West', 'Powai', 'Jogeshwari', 'Malad', 'Borivali', 'Mira Road'], 'Boroughs': ['West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'West Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'North Mumbai', 'North Mumbai', 'North Mumbai', 'North Mumbai', 'North Mumbai'], 'Address': ['Dadar, Mumbai', 'Bandra West, Mumbai', 'Juhu, Mumbai', 'Andheri, Mumbai', 'Kalina, Mumbai', 'Santa Cruz, Mumbai', 'Mahim, Mumbai', 'Khar, Mumbai', 'Kurla, Mumbai', 'Ghatkopar, Mumbai', 'Chembur, Mumbai', 'Govandi, Mumbai', 'Mulund West, Mumbai', 'Powai, Mumbai', 'Jogeshwari, Mumbai', 'Malad, Mumbai', 'Borivali, Mumbai', 'Mira Road, Mumbai']}

In [18]:
df_area1 = pd.DataFrame.from_dict(dic_area1)
df_area1.head()
#df_area1.to_csv("mumbai_south_neighborhood_all.csv")

    Neighborhood      Boroughs                Address
0         Colaba  South Mumbai         Colaba, Mumbai
1  Apollo Bandar  South Mumbai  Apollo Bandar, Mumbai
2           Fort  South Mumbai           Fort, Mumbai
3     Churchgate  South Mumbai     Churchgate, Mumbai
4  Nariman Point  South Mumbai  Nariman Point, Mumbai

In [19]:
df_area2 = pd.DataFrame.from_dict(dic_area2)
df_area2.tail()
#df_area2.to_csv("mumbai_south_neighborhood_all.csv")

   Neighborhood      Boroughs             Address
13        Powai  North Mumbai       Powai, Mumbai
14   Jogeshwari  North Mumbai  Jogeshwari, Mumbai
15        Malad  North Mumbai       Malad, Mumbai
16     Borivali  North Mumbai    Borivali, Mumbai
17    Mira Road  North Mumbai   Mira Road, Mumbai

### **Let's pass south Mumbai :  df_area1**

In [20]:
df2 = df_area1
df2.shape
df2.head()

    Neighborhood      Boroughs                Address
0         Colaba  South Mumbai         Colaba, Mumbai
1  Apollo Bandar  South Mumbai  Apollo Bandar, Mumbai
2           Fort  South Mumbai           Fort, Mumbai
3     Churchgate  South Mumbai     Churchgate, Mumbai
4  Nariman Point  South Mumbai  Nariman Point, Mumbai

In [21]:
data = []
for  neighborhood,address,borough in zip(df2['Neighborhood'], df2['Address'],df2['Boroughs']):
  #print("neighborhood:", neighborhood)
  #print("address:", address)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  #print("latitude:", latitude)
  #print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
neighborhoods.head()

dtypes :  Neighborhood     object
Borough          object
Latitude        float64
Longitude       float64
dtype: object
rows :  21

    Neighborhood       Borough   Latitude  Longitude
0         Colaba  South Mumbai  18.915091  72.825969
1  Apollo Bandar  South Mumbai  18.918375  72.831443
2           Fort  South Mumbai  18.933266  72.834515
3     Churchgate  South Mumbai  18.935957  72.827340
4  Nariman Point  South Mumbai  18.925951  72.823208

In [22]:
neighborhoods1 = neighborhoods
neighborhoods1.to_csv("south_mumbai_latitudes.csv")
neighborhoods1.tail()

      Neighborhood       Borough   Latitude  Longitude
16      Grand Road  South Mumbai  18.938771  72.835335
17         Mazgaon  South Mumbai  18.968052  72.840012
18  Mumbai Central  South Mumbai  18.969586  72.819315
19       Mahalaxmi  South Mumbai  18.982568  72.824160
20           Worli  South Mumbai  19.011696  72.818070

### **Now let's pass east+west+north Mumabi : df_area2**

In [23]:
df2 = df_area2
df2.shape

(18, 3)

In [24]:
data = []
for  neighborhood,address,borough in zip(df2['Neighborhood'], df2['Address'],df2['Boroughs']):
  print("neighborhood:", neighborhood)
  print("address:", address)
  print("borough:", borough)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  print("latitude:", latitude)
  print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
#neighborhoods.head()

neighborhood: Dadar
address: Dadar, Mumbai
borough: West Mumbai
latitude: 19.019282
longitude: 72.8428757
neighborhood: Bandra West
address: Bandra West, Mumbai
borough: West Mumbai
latitude: 19.0583358
longitude: 72.8302669
neighborhood: Juhu
address: Juhu, Mumbai
borough: West Mumbai
latitude: 19.1070215
longitude: 72.8275275
neighborhood: Andheri
address: Andheri, Mumbai
borough: West Mumbai
latitude: 19.1196976
longitude: 72.8464205
neighborhood: Kalina
address: Kalina, Mumbai
borough: West Mumbai
latitude: 19.079273
longitude: 72.8612672
neighborhood: Santa Cruz
address: Santa Cruz, Mumbai
borough: West Mumbai
latitude: 19.0793694
longitude: 72.8470855
neighborhood: Mahim
address: Mahim, Mumbai
borough: West Mumbai
latitude: 19.0423145
longitude: 72.8398344
neighborhood: Khar
address: Khar, Mumbai
borough: West Mumbai
latitude: 19.0696584
longitude: 72.8398944
neighborhood: Kurla
address: Kurla, Mumbai
borough: East Mumbai
latitude: 19.0652797
longitude: 72.8793805
neighborhood: Ghatkopar
address: Ghatkopar, Mumbai
borough: East Mumbai
latitude: 19.0859539
longitude: 72.9082381
neighborhood: Chembur
address: Chembur, Mumbai
borough: East Mumbai
latitude: 19.0612128
longitude: 72.8975909
neighborhood: Govandi
address: Govandi, Mumbai
borough: East Mumbai
latitude: 19.0553688
longitude: 72.9150702
neighborhood: Mulund West
address: Mulund West, Mumbai
borough: East Mumbai
latitude: 19.1719717
longitude: 72.9511956
neighborhood: Powai
address: Powai, Mumbai
borough: North Mumbai
latitude: 19.1187195
longitude: 72.9073476
neighborhood: Jogeshwari
address: Jogeshwari, Mumbai
borough: North Mumbai
latitude: 19.1348994
longitude: 72.8488199
neighborhood: Malad
address: Malad, Mumbai
borough: North Mumbai
latitude: 19.1867193
longitude: 72.8485884
neighborhood: Borivali
address: Borivali, Mumbai
borough: North Mumbai
latitude: 19.229068
longitude: 72.8573628
neighborhood: Mira Road
address: Mira Road, Mumbai
borough: North Mumbai
latitude: 19.1878962
longitude: 72.8365955
dtypes :  Neighborhood     object
Borough          object
Latitude        float64
Longitude       float64
dtype: object
rows :  18

In [25]:
neighborhoods2 = neighborhoods
neighborhoods2.shape # (19, 4)
neighborhoods2.head()
neighborhoods2.tail()

   Neighborhood       Borough   Latitude  Longitude
13        Powai  North Mumbai  19.118720  72.907348
14   Jogeshwari  North Mumbai  19.134899  72.848820
15        Malad  North Mumbai  19.186719  72.848588
16     Borivali  North Mumbai  19.229068  72.857363
17    Mira Road  North Mumbai  19.187896  72.836596

In [26]:
neighborhoods2.tail()

   Neighborhood       Borough   Latitude  Longitude
13        Powai  North Mumbai  19.118720  72.907348
14   Jogeshwari  North Mumbai  19.134899  72.848820
15        Malad  North Mumbai  19.186719  72.848588
16     Borivali  North Mumbai  19.229068  72.857363
17    Mira Road  North Mumbai  19.187896  72.836596

## **Now Let's concat two dataframes**

In [27]:
neighborhoods = neighborhoods1.append(neighborhoods2,ignore_index=True)
neighborhoods.shape
#neighborhoods.head(40)
#result = df1.append(df2)
#bigdata = data1.append(data2, ignore_index=True)

(39, 4)

In [0]:
neighborhoods = neighborhoods.reset_index()

In [29]:
print("Merged data frame have rows.", neighborhoods.shape[0])
neighborhoods.to_csv("all_mumbai_latitude.csv")
neighborhoods.tail()

Merged data frame have rows. 39

    index Neighborhood       Borough   Latitude  Longitude
34     34        Powai  North Mumbai  19.118720  72.907348
35     35   Jogeshwari  North Mumbai  19.134899  72.848820
36     36        Malad  North Mumbai  19.186719  72.848588
37     37     Borivali  North Mumbai  19.229068  72.857363
38     38    Mira Road  North Mumbai  19.187896  72.836596

In [0]:
neighborhoods.to_csv("Mumbai_locations2.csv")

### Use geopy library to get the latitude and longitude values of Mumbai
### In order to define an instance of the geocoder, we need to define a user_agent. We will name our agent ny_explorer, as shown below.

### Create a map of Mumbai with neighborhoods superimposed on top.

In [30]:
# Mumbai : Latitude: 18.9600 Longitude: 72.8200
latitude = 18.9600
longitude = 72.8200
map_mumbai = folium.Map(location=[latitude, longitude], zoom_start=14)
map_mumbai

In [31]:

# add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_mumbai)  
    
map_mumbai

### Define Foursquare Credentials and Version

In [32]:
CLIENT_ID = 'AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC' # your Foursquare ID
CLIENT_SECRET = '5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC
CLIENT_SECRET:5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH

### Let's create a function to repeat the same process to all the neighborhoods in South Mumbai

In [0]:
radius=650
LIMIT = 100
print("The radius is = {} and LIMIT is = {}".format(radius,LIMIT))

The radius is = 650 and LIMIT is = 100

In [0]:
LIMIT = 100
def getNearbyVenues(names, latitudes, longitudes, radius=650):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

### Now write the code to run the above function on each neighborhood and create a new dataframe called south_mumbai_venues.

In [0]:
south_mumbai_data = neighborhoods
#print("dtypes:",south_mumbai_data.dtypes)
#print("shape:",south_mumbai_data.shape)
#south_mumbai_data.head()

In [41]:
south_mumbai_venues = getNearbyVenues(names=south_mumbai_data['Neighborhood'],
                                   latitudes=south_mumbai_data['Latitude'],
                                   longitudes=south_mumbai_data['Longitude']
                                   
                                  )
print("dtypes:",south_mumbai_venues.dtypes)
print("Total venues retrieved:",south_mumbai_venues.shape[0])

#south_mumbai_venues.head()

Colaba
Apollo Bandar
Fort
Churchgate
Nariman Point
Marine Lines
Walkeshwar
Malabar Hill
Kalbadevi
Bhuleshwar
Masjid Bandar
Darukhana
Pydhoni
Nagpada
Dongri
Byculla
Grand Road
Mazgaon
Mumbai Central
Mahalaxmi
Worli
Dadar
Bandra West
Juhu
Andheri
Kalina
Santa Cruz
Mahim
Khar
Kurla
Ghatkopar
Chembur
Govandi
Mulund West
Powai
Jogeshwari
Malad
Borivali
Mira Road
dtypes: Neighborhood               object
Neighborhood Latitude     float64
Neighborhood Longitude    float64
Venue                      object
Venue Latitude            float64
Venue Longitude           float64
Venue Category             object
dtype: object
Total venues retrieved: 1104

In [42]:
south_mumbai_venues.head()

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.821080    Thai Restaurant
3       Colaba              18.915091  ...        72.829185       Dessert Shop
4       Colaba              18.915091  ...        72.821028              Hotel

[5 rows x 7 columns]

# **Add Museum**

### One of the key venue the biggest and most significant Museum of Mumbai not returned by Four Square API. Added this record.

In [47]:
south_mumbai_venues_append_test = south_mumbai_venues
south_mumbai_venues_append_test.tail()
#print("as")
south_mumbai_venues_append_test.columns
south_mumbai_venues_append_test.dtypes

south_mumbai_venues_append_test

index                       int64
Neighborhood               object
Neighborhood Latitude     float64
Neighborhood Longitude    float64
Venue                      object
Venue Latitude            float64
Venue Longitude           float64
Venue Category             object
dtype: object

In [53]:
print("row bef add:",south_mumbai_venues_append_test.shape[0])
south_mumbai_venues_append_test.append({'index':1104, \
                                        'Neighborhood': 'Apollo Bandar', \
                                        'Neighborhood Latitude':18.9183748, \
                                        'Neighborhood Longitude':72.8314429, \
                                        'Venue':'Prince Albert Museum', \
                                        'Venue Latitude':18.9269, \
                                        'Venue Longitude':72.8327, \
                                        'Venue Category':'History Museum' \
                                        },ignore_index=True)

print("row aft add:",south_mumbai_venues_append_test.shape[0])

south_mumbai_venues_append_test.tail()

#f.append({'Animal':'mouse', 'Color':'black'}, ignore_index=True)

row bef add: 938
row aft add: 938

     index Neighborhood  ...  Venue Longitude        Venue Category
933   1099    Mira Road  ...        72.833399                Bakery
934   1100    Mira Road  ...        72.835840                 Diner
935   1101    Mira Road  ...        72.840819        Breakfast Spot
936   1102    Mira Road  ...        72.842250  Fast Food Restaurant
937   1103    Mira Road  ...        72.841896      Department Store

[5 rows x 8 columns]

In [0]:
south_mumbai_venues_append_test.to_csv("all_mumbai_venues_museum1.csv")

# Test : **Try Concat**

In [52]:
south_mumbai_venues_append_test.dtypes

index                       int64
Neighborhood               object
Neighborhood Latitude     float64
Neighborhood Longitude    float64
Venue                      object
Venue Latitude            float64
Venue Longitude           float64
Venue Category             object
dtype: object

In [54]:
new_record = pd.DataFrame([1104,'Apollo Bandar',18.9183748,72.8314429,\
                           'Prince Albert Museum',18.9269,72.8327,'History Museum'], \
                          columns=['index','Neighborhood','Neighborhood Latitude', \
                                      'Neighborhood Longitude','Venue','Venue Latitude','Venue Longitude','Venue Category'])
new_record.head()
#new_record = pd.DataFrame([[0,'abcd',0,1,123]],columns=['a','b','c','d','e'])
#old_data_frame = pd.concat([old_data_frame,new_record])

ValueError: ignored

# **Drop Duplicates Venues**

In [0]:
duplicate1 = south_mumbai_venues
print("rows before dropping duplicates={}".format(duplicate1.shape[0]))
duplicate1 = duplicate1.drop_duplicates(subset=['Venue Latitude', 'Venue Longitude'])
print("rows after dropping duplicates={}".format(duplicate1.shape[0]))
#duplicate1.to_csv("south_mumbai_venues_no_duplicates.csv")
south_mumbai_venues.to_csv("all_mumbai_venues_650.csv")

rows before dropping duplicates=1104
rows after dropping duplicates=987

# **Remove rows with Indian Restaurants**.

In [0]:
#Backup dataframe
south_mumbai_venues_bkp = south_mumbai_venues
south_mumbai_indian_restaurants = south_mumbai_venues[(south_mumbai_venues['Venue Category'] == "Indian Restaurant")]
print("mumbai indian restaurants:",south_mumbai_indian_restaurants.shape[0])  #62
south_mumbai_indian_restaurants.head()
south_mumbai_indian_restaurants.to_csv("south_mumbai_indian_restaurants.csv")

#indian_restaurants: 165

mumbai indian restaurants: 169

In [0]:
#south_mumbai_venues.dtypes
print("rows bef drop:",south_mumbai_venues.shape[0])
south_mumbai_venues = south_mumbai_venues[(south_mumbai_venues['Venue Category'] != "Indian Restaurant")].reset_index()
print("rows aft drop:",south_mumbai_venues.shape[0])
south_mumbai_venues.to_csv("south_mumbai_minus_indian_restaurants.csv")
south_mumbai_venues.head()
#1125 to 960

rows bef drop: 1104
rows aft drop: 938

   index Neighborhood  ...  Venue Longitude     Venue Category
0      0       Colaba  ...        72.824151        Men's Store
1      1       Colaba  ...        72.827018  German Restaurant
2      2       Colaba  ...        72.821080    Thai Restaurant
3      3       Colaba  ...        72.829185       Dessert Shop
4      4       Colaba  ...        72.821028              Hotel

[5 rows x 8 columns]

In [0]:
south_mumbai_venues_x1 = south_mumbai_venues.groupby('Neighborhood').count()
south_mumbai_venues_x1.to_csv("all_mumbai_venues_x1_groupby.csv")

In [0]:
south_mumbai_venues_x1.head()

               index  Neighborhood Latitude  ...  Venue Longitude  Venue Category
Neighborhood                                 ...
Andheri           12                     12  ...               12              12
Apollo Bandar     62                     62  ...               62              62
Bandra West       88                     88  ...               88              88
Bhuleshwar        17                     17  ...               17              17
Borivali          28                     28  ...               28              28

[5 rows x 7 columns]

In [0]:
south_mumbai_venues_categories_x2 = south_mumbai_venues.groupby('Venue Category').count()
south_mumbai_venues_categories_x2.to_csv("all_mumbai_venues_categories_x2_groupby.csv")
south_mumbai_venues_categories_x2.head()
south_mumbai_venues_categories_x2.tail()

                index  Neighborhood  ...  Venue Latitude  Venue Longitude
Venue Category                       ...
Video Store         1             1  ...               1                1
Wine Bar            2             2  ...               2                2
Women's Store       4             4  ...               4                4
Yoga Studio         1             1  ...               1                1
Zoo                 1             1  ...               1                1

[5 rows x 7 columns]

## **Unique Categories**

In [0]:
### Let's find out how many unique categories can be curated from all the returned venues

print('There are {} uniques categories.'.format(len(south_mumbai_venues['Venue Category'].unique())))
# 158

There are 159 uniques categories.

In [51]:
### 3. Analyze Each Neighborhood

# one hot encoding
south_mumbai_onehot = pd.get_dummies(south_mumbai_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
south_mumbai_onehot['Neighborhood'] = south_mumbai_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [south_mumbai_onehot.columns[-1]] + list(south_mumbai_onehot.columns[:-1])
south_mumbai_onehot = south_mumbai_onehot[fixed_columns]

south_mumbai_onehot.head()
south_mumbai_onehot.shape

(1104, 157)

In [0]:
south_mumbai_onehot_test.to_csv("south_mumbai_onehot_test1.csv")

In [0]:
south_mumbai_onehot.to_csv("south_mumbai_onehot.csv")

In [0]:
#And let's examine the new dataframe size.
south_mumbai_onehot.shape  # (359, 105) (292,103)

(966, 160)

# **TWEAK HERE**

In [56]:
df_test_one_hot = pd.read_csv("south_mumbai_onehot.csv")
df_test_one_hot.shape

#df = pd.read_csv(

(1104, 158)

In [59]:
south_mumbai_grouped_test = df_test_one_hot.groupby('Neighborhood').mean().reset_index()
south_mumbai_grouped_test.shape

(39, 158)

In [0]:
south_mumbai_grouped_test.to_csv("south_mumbai_grouped_test.csv")

In [54]:
#Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

south_mumbai_grouped = south_mumbai_onehot.groupby('Neighborhood').mean().reset_index()
south_mumbai_grouped

      Neighborhood  Accessories Store  ...  Yoga Studio       Zoo
0          Andheri           0.000000  ...     0.000000  0.000000
1    Apollo Bandar           0.000000  ...     0.000000  0.000000
2      Bandra West           0.000000  ...     0.000000  0.000000
3       Bhuleshwar           0.000000  ...     0.000000  0.000000
4         Borivali           0.000000  ...     0.000000  0.000000
5          Byculla           0.000000  ...     0.000000  0.111111
6          Chembur           0.031250  ...     0.000000  0.000000
7       Churchgate           0.000000  ...     0.000000  0.000000
8           Colaba           0.000000  ...     0.000000  0.000000
9            Dadar           0.000000  ...     0.000000  0.000000
10       Darukhana           0.000000  ...     0.000000  0.000000
11          Dongri           0.000000  ...     0.000000  0.000000
12            Fort           0.000000  ...     0.000000  0.000000
13       Ghatkopar           0.041667  ...     0.000000  0.000000
14         Govandi           0.000000  ...     0.000000  0.000000
15      Grand Road           0.000000  ...     0.000000  0.000000
16      Jogeshwari           0.000000  ...     0.000000  0.000000
17            Juhu           0.000000  ...     0.000000  0.000000
18       Kalbadevi           0.000000  ...     0.000000  0.000000
19          Kalina           0.000000  ...     0.000000  0.000000
20            Khar           0.000000  ...     0.000000  0.000000
21           Kurla           0.000000  ...     0.000000  0.000000
22       Mahalaxmi           0.000000  ...     0.000000  0.000000
23           Mahim           0.000000  ...     0.000000  0.000000
24    Malabar Hill           0.000000  ...     0.000000  0.000000
25           Malad           0.000000  ...     0.000000  0.000000
26    Marine Lines           0.000000  ...     0.000000  0.000000
27   Masjid Bandar           0.000000  ...     0.000000  0.000000
28         Mazgaon           0.000000  ...     0.000000  0.000000
29       Mira Road           0.000000  ...     0.000000  0.000000
30     Mulund West           0.000000  ...     0.000000  0.000000
31  Mumbai Central           0.000000  ...     0.000000  0.000000
32         Nagpada           0.000000  ...     0.000000  0.000000
33   Nariman Point           0.000000  ...     0.000000  0.000000
34           Powai           0.000000  ...     0.000000  0.000000
35         Pydhoni           0.000000  ...     0.000000  0.000000
36      Santa Cruz           0.000000  ...     0.000000  0.000000
37      Walkeshwar           0.000000  ...     0.000000  0.000000
38           Worli           0.000000  ...     0.066667  0.000000

[39 rows x 157 columns]

In [0]:
south_mumbai_grouped.to_csv("south_mumbai_grouped.csv")

In [0]:
south_mumbai_grouped.to_csv("south_mumbai_grouped.csv")

In [0]:
south_mumbai_grouped.shape #(21, 105)->(21,103)

(21, 121)

In [0]:
## Let's print each neighborhood along with the top 5 most common venues

num_top_venues = 5

for hood in south_mumbai_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = south_mumbai_grouped[south_mumbai_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Andheri----
                  venue  freq
0  Fast Food Restaurant  0.25
1            Restaurant  0.17
2             Bookstore  0.08
3                Bakery  0.08
4            Food Court  0.08


----Apollo Bandar----
         venue  freq
0        Hotel  0.13
1         Café  0.08
2          Bar  0.08
3  Coffee Shop  0.05
4   Restaurant  0.05


----Bandra West----
                venue  freq
0                Café  0.10
1                 Bar  0.07
2              Bakery  0.07
3    Asian Restaurant  0.05
4  Chinese Restaurant  0.05


----Bhuleshwar----
            venue  freq
0  Ice Cream Shop  0.12
1           Hotel  0.06
2       BBQ Joint  0.06
3     Snack Place  0.06
4            Café  0.06


----Borivali----
                           venue  freq
0                 Ice Cream Shop  0.11
1                 Clothing Store  0.11
2             Chinese Restaurant  0.11
3  Vegetarian / Vegan Restaurant  0.07
4                    Snack Place  0.07


----Byculla----
              venue  freq
0            Bakery  0.29
1               Zoo  0.14
2  Asian Restaurant  0.14
3               Bar  0.14
4       Pizza Place  0.14


----Chembur----
                           venue  freq
0             Seafood Restaurant  0.13
1                     Restaurant  0.09
2                            Gym  0.09
3                           Café  0.09
4  Vegetarian / Vegan Restaurant  0.09


----Churchgate----
                  venue  freq
0  Fast Food Restaurant  0.08
1                 Hotel  0.07
2        Cricket Ground  0.07
3        Ice Cream Shop  0.07
4    Italian Restaurant  0.05


----Colaba----
                venue  freq
0          Restaurant  0.10
1         Coffee Shop  0.10
2               Hotel  0.07
3                 Spa  0.07
4  Chinese Restaurant  0.07


----Dadar----
                  venue  freq
0                  Café  0.11
1  Fast Food Restaurant  0.11
2           Coffee Shop  0.11
3         Movie Theater  0.07
4        Breakfast Spot  0.07


----Darukhana----
                 venue  freq
0                  ATM   0.2
1  Arts & Crafts Store   0.2
2                 Café   0.2
3          Flea Market   0.2
4           Restaurant   0.2


----Dongri----
           venue  freq
0    Music Venue  0.33
1   Dessert Shop  0.33
2     Restaurant  0.33
3            ATM  0.00
4  Movie Theater  0.00


----Fort----
                  venue  freq
0                  Café  0.09
1    Chinese Restaurant  0.06
2    Seafood Restaurant  0.06
3  Fast Food Restaurant  0.05
4          Dessert Shop  0.05


----Ghatkopar----
               venue  freq
0        Pizza Place  0.10
1          Juice Bar  0.10
2             Bakery  0.10
3    Bed & Breakfast  0.05
4  Accessories Store  0.05


----Govandi----
                           venue  freq
0  Paper / Office Supplies Store   0.2
1                       Platform   0.2
2              Food & Drink Shop   0.2
3                     Food Truck   0.2
4                           Park   0.2


----Grand Road----
                venue  freq
0  Seafood Restaurant  0.12
1                Café  0.12
2          Irani Cafe  0.08
3  Chinese Restaurant  0.08
4                 Bar  0.08


----Jogeshwari----
                venue  freq
0    Halal Restaurant  0.17
1      Ice Cream Shop  0.17
2  Mughlai Restaurant  0.17
3    Asian Restaurant  0.17
4  Chinese Restaurant  0.17


----Juhu----
                venue  freq
0                 Bar  0.10
1                Café  0.10
2               Hotel  0.08
3  Chinese Restaurant  0.08
4        Cocktail Bar  0.05


----Kalbadevi----
                  venue  freq
0  Fast Food Restaurant  0.17
1                  Café  0.17
2                Market  0.08
3         Train Station  0.08
4           Cheese Shop  0.08


----Kalina----
                venue  freq
0  Chinese Restaurant  0.12
1             Airport  0.12
2        Burger Joint  0.12
3  Seafood Restaurant  0.12
4      Ice Cream Shop  0.12


----Khar----
                  venue  freq
0                   Bar  0.11
1                   Pub  0.07
2                Lounge  0.07
3  Fast Food Restaurant  0.07
4  Gym / Fitness Center  0.04


----Kurla----
                           venue  freq
0                     Shoe Store   0.2
1  Vegetarian / Vegan Restaurant   0.2
2                  Train Station   0.2
3            Arts & Crafts Store   0.2
4               Asian Restaurant   0.2


----Mahalaxmi----
                  venue  freq
0           Coffee Shop  0.22
1             Nightclub  0.11
2  Fast Food Restaurant  0.11
3                Bakery  0.11
4            Club House  0.11


----Mahim----
                  venue  freq
0        Breakfast Spot   0.1
1           Pizza Place   0.1
2             Hotel Bar   0.1
3                Arcade   0.1
4  Fast Food Restaurant   0.1


----Malabar Hill----
                  venue  freq
0                  Park  0.18
1                Bakery  0.18
2          Dessert Shop  0.18
3            Restaurant  0.09
4  Fast Food Restaurant  0.09


----Malad----
                  venue  freq
0           Snack Place   0.2
1  Fast Food Restaurant   0.2
2          Dessert Shop   0.2
3        Breakfast Spot   0.1
4              Platform   0.1


----Marine Lines----
         venue  freq
0       Bakery  0.10
1         Café  0.10
2   Food Truck  0.05
3  Bridal Shop  0.05
4  Snack Place  0.05


----Masjid Bandar----
               venue  freq
0    Harbor / Marina  0.21
1              Hotel  0.11
2  Convenience Store  0.11
3               Café  0.11
4       Dessert Shop  0.05


----Mazgaon----
                  venue  freq
0     Convenience Store  0.09
1    Chinese Restaurant  0.09
2  Fast Food Restaurant  0.09
3        Ice Cream Shop  0.09
4                   Gym  0.09


----Mira Road----
                  venue  freq
0  Fast Food Restaurant  0.07
1                   Bar  0.07
2                   Pub  0.07
3        Clothing Store  0.07
4           Coffee Shop  0.05


----Mulund West----
                  venue  freq
0  Fast Food Restaurant  0.21
1          Dessert Shop  0.11
2        Ice Cream Shop  0.11
3           Bus Station  0.11
4               Theater  0.11


----Mumbai Central----
                  venue  freq
0  Fast Food Restaurant  0.21
1      Department Store  0.16
2           Snack Place  0.11
3        Ice Cream Shop  0.11
4           Pizza Place  0.05


----Nagpada----
                  venue  freq
0    Chinese Restaurant  0.17
1  Fast Food Restaurant  0.17
2      Department Store  0.11
3           Pizza Place  0.06
4                Bakery  0.06


----Nariman Point----
                  venue  freq
0    Italian Restaurant  0.09
1                 Hotel  0.07
2               Theater  0.07
3  Fast Food Restaurant  0.07
4            Restaurant  0.07


----Powai----
                venue  freq
0                 Bar  0.05
1      Ice Cream Shop  0.05
2  Chinese Restaurant  0.05
3         Coffee Shop  0.05
4          Restaurant  0.05


----Pydhoni----
               venue  freq
0              Hotel  0.12
1               Café  0.12
2             Bakery  0.06
3  Indian Sweet Shop  0.06
4          Juice Bar  0.06


----Santa Cruz----
                  venue  freq
0                 Hotel  0.12
1  Gym / Fitness Center  0.06
2      Asian Restaurant  0.06
3                  Café  0.06
4            Food Court  0.06


----Walkeshwar----
                  venue  freq
0  Fast Food Restaurant  0.08
1        Ice Cream Shop  0.08
2            Restaurant  0.08
3            Steakhouse  0.04
4             Juice Bar  0.04


----Worli----
                           venue  freq
0                 Scenic Lookout  0.22
1                           Café  0.17
2  Paper / Office Supplies Store  0.06
3                      Gun Range  0.06
4              French Restaurant  0.06

In [0]:
#Let's put that into a pandas dataframe
#First, let's write a function to sort the venues in descending orde

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [0]:
#Now let's create the new dataframe and display the top 10 venues for each neighborhood.

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = south_mumbai_grouped['Neighborhood']

for ind in np.arange(south_mumbai_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(south_mumbai_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

    Neighborhood  ... 10th Most Common Venue
0        Andheri  ...                    Zoo
1  Apollo Bandar  ...    Japanese Restaurant
2    Bandra West  ...            Pizza Place
3     Bhuleshwar  ...              BBQ Joint
4       Borivali  ...         Breakfast Spot

[5 rows x 11 columns]

In [0]:
neighborhoods_venues_sorted.to_csv("south_mumbai_top10_venue_categories_minus_indian_rest.csv")

# **Cluster Neighborhood**

## **Run k-means. Adjust number of clusters to optimum.**

In [0]:
# Run k-means to cluster the neighborhood into 5 clusters.
# Try with more clusters and see results.
# set number of clusters
#kclusters = 5 # First Iteration
#kclusters = 10 # Second Iteration
#kclusters = 5 # Third Iteration after removing Indian restaurants
kclusters = 10 # Fourth Iteration after removing Indian restaurants

In [0]:
# 4. Cluster Neighborhoods
south_mumbai_grouped_clustering = south_mumbai_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(south_mumbai_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([1, 4, 6, 1, 6, 5, 6, 1, 4, 1], dtype=int32)

In [0]:
### Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

In [0]:
neighborhoods_venues_sorted.dtypes

Cluster Labels             int32
Neighborhood              object
1st Most Common Venue     object
2nd Most Common Venue     object
3rd Most Common Venue     object
4th Most Common Venue     object
5th Most Common Venue     object
6th Most Common Venue     object
7th Most Common Venue     object
8th Most Common Venue     object
9th Most Common Venue     object
10th Most Common Venue    object
dtype: object

In [0]:
### Now merge both dataframes

south_mumbai_merged = south_mumbai_data

# merge two dataframes
south_mumbai_merged = south_mumbai_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

south_mumbai_merged.head() 
# check 'Cluster Labels' column has been added to dataframe

   index   Neighborhood  ... 9th Most Common Venue    10th Most Common Venue
0      0         Colaba  ...   Japanese Restaurant                       Pub
1      1  Apollo Bandar  ...          Cocktail Bar       Japanese Restaurant
2      2           Fort  ...      Parsi Restaurant                     Plaza
3      3     Churchgate  ...         Movie Theater               Pizza Place
4      4  Nariman Point  ...                 Diner  Mediterranean Restaurant

[5 rows x 16 columns]

# **Drop rows with missing data**

In [0]:
#df.dropna(subset = ['column1_name', 'column2_name', 'column3_name'])
print("rows bef:",south_mumbai_merged.shape[0])
south_mumbai_merged.dropna()
print("rows aft:",south_mumbai_merged.shape[0])

rows bef: 39
rows aft: 39

#### No row with any missing data found.

In [0]:
#south_mumbai_merged.dtypes #Cluster Labels float64
#south_mumbai_merged[["Cluster Labels"]] = south_mumbai_merged[["Cluster Labels"]].astype(int)
south_mumbai_merged.dtypes

index                       int64
Neighborhood               object
Borough                    object
Latitude                  float64
Longitude                 float64
Cluster Labels              int32
1st Most Common Venue      object
2nd Most Common Venue      object
3rd Most Common Venue      object
4th Most Common Venue      object
5th Most Common Venue      object
6th Most Common Venue      object
7th Most Common Venue      object
8th Most Common Venue      object
9th Most Common Venue      object
10th Most Common Venue     object
dtype: object

In [0]:
south_mumbai_merged.to_csv("all_mumbai_cluster_k10_r650.csv")

In [0]:
#Finally, let's visualize the resulting clusters
#South Mumbai Latitude: 18.9600 Longitude: 72.8200
latitude  = 18.9600
longitude = 72.8200

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(south_mumbai_merged['Latitude'], south_mumbai_merged['Longitude'], south_mumbai_merged['Neighborhood'], south_mumbai_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

# **This concludes the iteration No . Thank You.**

In [1]:
print("147KK")

147KK