# Cluster South Mumbai

#### In this analysis, the focus was South Mumbai, which is precisely area for foreign tourists. It is full of restaurants,hotelsand other places of entertainment.
### But upon complete analysis we noticed that most of the areas fall under single cluster. This can be due to Indian Restaurant.

#### Therefore, I decided to do a second iteration,by increasing number of clusters to 10 and see if clustering looks Okay.

Later a third iteration can be tried by discarding Indian restuarant and see how clusters change.

### A fourth iteration can be done with hybrid approach ie by discarding Indian Restaurant and increasing number of clusters at the same time.

#### A sixth iteration can be done by increasing number of areas from other parts of the city as well. It seems that entire South Mumbai by and large has similar charactersitics.

### A fifth iteration can be done by increasing radius to 900 m.

### Seventh iteration : Another question we may resolve is by comparing two different boroughs of Mumbai say South Mumbai and North Mumbai. How similar and how different they are.

#### By increasing radius, lot of overlappring of nearby neighborhood happened, and many duplicate venues appeared. These duplicates can be eliminated.

**Library**

### So, Let's begin second iteration.

In [3]:
import pandas as pd
from pandas.io.json import json_normalize  # tranform JSON file into a pandas dataframe

import numpy as np

from bs4 import BeautifulSoup

# Matplotlib and associated plotting modules
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.colors as colors

import seaborn as sns
from urllib.request import urlopen

import requests
# import k-means from clustering stage
from sklearn.cluster import KMeans

print("Library imported 71.")

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

Library imported 71.

In [4]:
import folium # map rendering library
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
print("Library imported 72.")

Library imported 72.

In [0]:
areas_south = ["Colaba","Apollo Bandar","Fort","Churchgate","Nariman Point" \
        ,"Marine Lines","Walkeshwar","Malabar Hill","Kalbadevi","Bhuleshwar" \
        ,"Masjid Bandar","Darukhana","Pydhoni","Nagpada","Dongri" \
        ,"Byculla","Grand Road","Mazgaon","Mumbai Central","Mahalaxmi" \
        ,"Worli"]
#areas_south

In [0]:
areas_west = ["Dadar","Bandra West","Juhu","Aksa Beach","Andheri" \
              "Kalina","Santa Cruz","Mahim","Khar"]
        
#areas_west

In [90]:
areas_east = ["Kurla","Ghatkopar","Chembur","Govandi","Mulund West"] 
areas_east

['Kurla', 'Ghatkopar', 'Chembur', 'Govandi', 'Mulund West']

In [92]:
areas_north = ["Powai","Jogeshwari","Malad","Borivali","Mira Road"] 
areas_north

['Powai', 'Jogeshwari', 'Malad', 'Borivali', 'Mira Road']

In [0]:
areas2 = ["Colaba","Apollo Bandar","Fort","Churchgate","Nariman Point"
        ,"Marine Lines","Walkeshwar","Malabar Hill","Kalbadevi"
        ,"Bhuleshwar","Masjid Bandar","Darukhana","Pydhoni","Nagpada","Dongri","Byculla","Grand Road"
        ,"Mazgaon","Mumbai Central","Mahalaxmi","Worli"
]
areas3 = ["Ghatkopar"]
areas4 = ["Chembur"]
areas5 = areas3 + areas4

In [0]:
boroughs_south_mumbai = ["South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai","South Mumbai","South Mumbai","South Mumbai","South Mumbai", \
             "South Mumbai"]
#boroughs_south_mumbai

In [0]:
boroughs_west_mumbai = ["West Mumbai","West Mumbai","West Mumbai","West Mumbai","West Mumbai", \
             "West Mumbai","West Mumbai","West Mumbai","West Mumbai"]
             
            
#boroughs_west_mumbai

In [81]:
boroughs_east_mumbai = ["East Mumbai","East Mumbai","East Mumbai","East Mumbai","East Mumbai"]
boroughs_east_mumbai

['East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai', 'East Mumbai']

In [82]:
boroughs_north_mumbai = ["North Mumbai","North Mumbai","North Mumbai","North Mumbai","North Mumbai"]
boroughs_north_mumbai

['North Mumbai',
 'North Mumbai',
 'North Mumbai',
 'North Mumbai',
 'North Mumbai']

In [0]:
boroughs = boroughs_south_mumbai + boroughs_west_mumbai + boroughs_east_mumbai + boroughs_north_mumbai
#boroughs

In [0]:
full_address = []
 
for area in areas:
   
  full_address.append(area + ", Mumbai")

In [0]:
dic_test1 = {"Neighborhood": areas,"Boroughs": boroughs,"Address":full_address}

In [0]:
df_test1 = pd.DataFrame.from_dict(dic_test1)
df_test1

In [0]:
areas = areas1

### **Let's Explore venues in South Mumbai **

In [7]:

full_address = []
 
for area in areas:
   
  full_address.append(area + ", Mumbai")

print("full_address",full_address)
print("areas",areas)

full_address ['Colaba, Mumbai', 'Apollo Bandar, Mumbai', 'Fort, Mumbai', 'Churchgate, Mumbai', 'Nariman Point, Mumbai', 'Marine Lines, Mumbai', 'Walkeshwar, Mumbai', 'Malabar Hill, Mumbai', 'Kalbadevi, Mumbai', 'Bhuleshwar, Mumbai', 'Masjid Bandar, Mumbai', 'Darukhana, Mumbai', 'Pydhoni, Mumbai', 'Nagpada, Mumbai', 'Dongri, Mumbai', 'Byculla, Mumbai', 'Grand Road, Mumbai', 'Mazgaon, Mumbai', 'Mumbai Central, Mumbai', 'Mahalaxmi, Mumbai', 'Worli, Mumbai']
areas ['Colaba', 'Apollo Bandar', 'Fort', 'Churchgate', 'Nariman Point', 'Marine Lines', 'Walkeshwar', 'Malabar Hill', 'Kalbadevi', 'Bhuleshwar', 'Masjid Bandar', 'Darukhana', 'Pydhoni', 'Nagpada', 'Dongri', 'Byculla', 'Grand Road', 'Mazgaon', 'Mumbai Central', 'Mahalaxmi', 'Worli']

In [8]:

dic1 = {"Neighborhood": areas,"Address":full_address}
dic1

{'Address': ['Colaba, Mumbai',
  'Apollo Bandar, Mumbai',
  'Fort, Mumbai',
  'Churchgate, Mumbai',
  'Nariman Point, Mumbai',
  'Marine Lines, Mumbai',
  'Walkeshwar, Mumbai',
  'Malabar Hill, Mumbai',
  'Kalbadevi, Mumbai',
  'Bhuleshwar, Mumbai',
  'Masjid Bandar, Mumbai',
  'Darukhana, Mumbai',
  'Pydhoni, Mumbai',
  'Nagpada, Mumbai',
  'Dongri, Mumbai',
  'Byculla, Mumbai',
  'Grand Road, Mumbai',
  'Mazgaon, Mumbai',
  'Mumbai Central, Mumbai',
  'Mahalaxmi, Mumbai',
  'Worli, Mumbai'],
 'Neighborhood': ['Colaba',
  'Apollo Bandar',
  'Fort',
  'Churchgate',
  'Nariman Point',
  'Marine Lines',
  'Walkeshwar',
  'Malabar Hill',
  'Kalbadevi',
  'Bhuleshwar',
  'Masjid Bandar',
  'Darukhana',
  'Pydhoni',
  'Nagpada',
  'Dongri',
  'Byculla',
  'Grand Road',
  'Mazgaon',
  'Mumbai Central',
  'Mahalaxmi',
  'Worli']}

In [9]:
df2 = pd.DataFrame.from_dict(dic1)
df2

      Neighborhood                 Address
0           Colaba          Colaba, Mumbai
1    Apollo Bandar   Apollo Bandar, Mumbai
2             Fort            Fort, Mumbai
3       Churchgate      Churchgate, Mumbai
4    Nariman Point   Nariman Point, Mumbai
5     Marine Lines    Marine Lines, Mumbai
6       Walkeshwar      Walkeshwar, Mumbai
7     Malabar Hill    Malabar Hill, Mumbai
8        Kalbadevi       Kalbadevi, Mumbai
9       Bhuleshwar      Bhuleshwar, Mumbai
10   Masjid Bandar   Masjid Bandar, Mumbai
11       Darukhana       Darukhana, Mumbai
12         Pydhoni         Pydhoni, Mumbai
13         Nagpada         Nagpada, Mumbai
14          Dongri          Dongri, Mumbai
15         Byculla         Byculla, Mumbai
16      Grand Road      Grand Road, Mumbai
17         Mazgaon         Mazgaon, Mumbai
18  Mumbai Central  Mumbai Central, Mumbai
19       Mahalaxmi       Mahalaxmi, Mumbai
20           Worli           Worli, Mumbai

In [10]:
## Note: This did not work in second iteration ?
## Note: But, in next iteration it worked !!!!
borough = 'South Mumbai'
data = []
for  neighborhood,address in zip(df2['Neighborhood'], df2['Address']):
  print("neighborhood:", neighborhood)
  print("address:", address)
  geolocator = Nominatim(user_agent="ny_explorer")
  location = geolocator.geocode(address)
  latitude = location.latitude
  longitude = location.longitude
  print("latitude:", latitude)
  print("longitude:", longitude)
  data.append([neighborhood,borough,latitude,longitude])

col_names =  ['Neighborhood', 'Borough', 'Latitude','Longitude']
neighborhoods = pd.DataFrame(data,columns=col_names)
print("dtypes : ", neighborhoods.dtypes)
print("rows : ", neighborhoods.shape[0])
neighborhoods.head()

neighborhood: Colaba
address: Colaba, Mumbai
latitude: 18.915091
longitude: 72.8259691
neighborhood: Apollo Bandar
address: Apollo Bandar, Mumbai
latitude: 18.9183748
longitude: 72.8314429
neighborhood: Fort
address: Fort, Mumbai
latitude: 18.9332665
longitude: 72.8345146
neighborhood: Churchgate
address: Churchgate, Mumbai
latitude: 18.9359567
longitude: 72.8273404
neighborhood: Nariman Point
address: Nariman Point, Mumbai
latitude: 18.9259514
longitude: 72.8232083
neighborhood: Marine Lines
address: Marine Lines, Mumbai
latitude: 18.9456701
longitude: 72.823781
neighborhood: Walkeshwar
address: Walkeshwar, Mumbai
latitude: 18.9553434
longitude: 72.8079469
neighborhood: Malabar Hill
address: Malabar Hill, Mumbai
latitude: 18.9581616
longitude: 72.8033665
neighborhood: Kalbadevi
address: Kalbadevi, Mumbai
latitude: 18.9492575
longitude: 72.8279382
neighborhood: Bhuleshwar
address: Bhuleshwar, Mumbai
latitude: 18.9537706
longitude: 72.8274755
neighborhood: Masjid Bandar
address: Masjid Bandar, Mumbai
latitude: 18.953598550000002
longitude: 72.8381264997544
neighborhood: Darukhana
address: Darukhana, Mumbai
latitude: 18.9770363
longitude: 72.8490768
neighborhood: Pydhoni
address: Pydhoni, Mumbai
latitude: 18.9539939
longitude: 72.8323786
neighborhood: Nagpada
address: Nagpada, Mumbai
latitude: 18.9681782
longitude: 72.8286009
neighborhood: Dongri
address: Dongri, Mumbai
latitude: 18.9622265
longitude: 72.836795
neighborhood: Byculla
address: Byculla, Mumbai
latitude: 18.9766219
longitude: 72.8327936
neighborhood: Grand Road
address: Grand Road, Mumbai
latitude: 18.9387711
longitude: 72.8353355
neighborhood: Mazgaon
address: Mazgaon, Mumbai
latitude: 18.9680519
longitude: 72.84001187036267
neighborhood: Mumbai Central
address: Mumbai Central, Mumbai
latitude: 18.9695855
longitude: 72.8193152
neighborhood: Mahalaxmi
address: Mahalaxmi, Mumbai
latitude: 18.9825679
longitude: 72.82416
neighborhood: Worli
address: Worli, Mumbai
latitude: 19.0116962
longitude: 72.8180702
dtypes :  Neighborhood     object
Borough          object
Latitude        float64
Longitude       float64
dtype: object
rows :  21

    Neighborhood       Borough   Latitude  Longitude
0         Colaba  South Mumbai  18.915091  72.825969
1  Apollo Bandar  South Mumbai  18.918375  72.831443
2           Fort  South Mumbai  18.933266  72.834515
3     Churchgate  South Mumbai  18.935957  72.827340
4  Nariman Point  South Mumbai  18.925951  72.823208

In [11]:
neighborhoods.head()

    Neighborhood       Borough   Latitude  Longitude
0         Colaba  South Mumbai  18.915091  72.825969
1  Apollo Bandar  South Mumbai  18.918375  72.831443
2           Fort  South Mumbai  18.933266  72.834515
3     Churchgate  South Mumbai  18.935957  72.827340
4  Nariman Point  South Mumbai  18.925951  72.823208

In [0]:
neighborhoods.to_csv("Mumbai_locations2.csv")

### Use geopy library to get the latitude and longitude values of New York City.
### In order to define an instance of the geocoder, we need to define a user_agent. We will name our agent ny_explorer, as shown below.

### Create a map of Mumbai with neighborhoods superimposed on top.

In [12]:
#South Mumbai : Latitude: 18.9600 Longitude: 72.8200
latitude = 18.9600
longitude = 72.8200
map_mumbai = folium.Map(location=[latitude, longitude], zoom_start=14)
map_mumbai

In [13]:

# add markers to map
for lat, lng, borough, neighborhood in zip(neighborhoods['Latitude'], neighborhoods['Longitude'], neighborhoods['Borough'], neighborhoods['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_mumbai)  
    
map_mumbai

### Define Foursquare Credentials and Version

In [14]:
CLIENT_ID = 'AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC' # your Foursquare ID
CLIENT_SECRET = '5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC
CLIENT_SECRET:5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH

### Let's create a function to repeat the same process to all the neighborhoods in South Mumbai

# Fifth Iteration with a radius = 900

In [22]:
radius=900
LIMIT = 100
print("The radius is = {} and LIMIT is = {}".format(radius,LIMIT))

The radius is = 900 and LIMIT is = 100

In [0]:
def getNearbyVenues(names, latitudes, longitudes, radius=700):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

### Now write the code to run the above function on each neighborhood and create a new dataframe called south_mumbai_venues.

In [0]:
south_mumbai_data = neighborhoods
#print("dtypes:",south_mumbai_data.dtypes)
#print("shape:",south_mumbai_data.shape)
#south_mumbai_data.head()

### Adjust radius here.

In [0]:
radius = 900

In [72]:
south_mumbai_venues = getNearbyVenues(names=south_mumbai_data['Neighborhood'],
                                   latitudes=south_mumbai_data['Latitude'],
                                   longitudes=south_mumbai_data['Longitude']
                                   
                                  )
print("dtypes:",south_mumbai_venues.dtypes)
print("Total venues retrieved:",south_mumbai_venues.shape[0])

south_mumbai_venues.head()

Colaba
Apollo Bandar
Fort
Churchgate
Nariman Point
Marine Lines
Walkeshwar
Malabar Hill
Kalbadevi
Bhuleshwar
Masjid Bandar
Darukhana
Pydhoni
Nagpada
Dongri
Byculla
Grand Road
Mazgaon
Mumbai Central
Mahalaxmi
Worli
dtypes: Neighborhood               object
Neighborhood Latitude     float64
Neighborhood Longitude    float64
Venue                      object
Venue Latitude            float64
Venue Longitude           float64
Venue Category             object
dtype: object
Total venues retrieved: 649

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.821080    Thai Restaurant
3       Colaba              18.915091  ...        72.829185       Dessert Shop
4       Colaba              18.915091  ...        72.821028              Hotel

[5 rows x 7 columns]

#**IGNORE : Test Code**

In [73]:
duplicate1 = south_mumbai_venues
print("How many rows before dropping duplicates={}".format(duplicate1.shape[0]))
duplicate1 = duplicate1.drop_duplicates(subset=['Venue Latitude', 'Venue Longitude'])
print("How many rows after dropping duplicates={}".format(duplicate1.shape[0]))
#duplicate1.to_csv("south_mumbai_venues_no_duplicates.csv")
south_mumbai_venues.to_csv("south_mumbai_venues_600.csv")

How many rows before dropping duplicates=649
How many rows after dropping duplicates=488

### It returned total 359 venues.
### Venues increased to 873 with a radius of 900.

# **Duplicates Issue**

### Are there any duplicates due to overlapping of areas.

# **Third Iteration**

### Remove rows with Indian Restaurants.

In [30]:
#Backup dataframe
south_mumbai_venues_bkp = south_mumbai_venues
south_mumbai_indian_restaurants = south_mumbai_venues[(south_mumbai_venues['Venue Category'] == "Indian Restaurant")]
print("south_mumbai_indian_restaurants:",south_mumbai_indian_restaurants.shape[0])  #62
south_mumbai_indian_restaurants.head()
south_mumbai_indian_restaurants.to_csv("south_mumbai_indian_restaurants.csv")

#indian_restaurants: 140

south_mumbai_indian_restaurants: 140

In [31]:
#south_mumbai_venues.dtypes
print("south_mumbai_venues:rows:bef:",south_mumbai_venues.shape[0])
south_mumbai_venues = south_mumbai_venues[(south_mumbai_venues['Venue Category'] != "Indian Restaurant")].reset_index()
print("south_mumbai_venues:rows:aft:",south_mumbai_venues.shape[0])
south_mumbai_venues.to_csv("south_mumbai_minus_indian_restaurants.csv")
south_mumbai_venues.head()
#353 to 292
#873 to 733

south_mumbai_venues:rows:bef: 873
south_mumbai_venues:rows:aft: 733

   index Neighborhood  ...  Venue Longitude     Venue Category
0      0       Colaba  ...        72.824151        Men's Store
1      1       Colaba  ...        72.821080    Thai Restaurant
2      2       Colaba  ...        72.827018  German Restaurant
3      3       Colaba  ...        72.829185       Dessert Shop
4      4       Colaba  ...        72.821028              Hotel

[5 rows x 8 columns]

# **IGNORE**

In [98]:
# Ignore: Note: This template code for getting venues city by city.
radius= 500
LIMIT = 200
#Esenyurt 41.0413° N, 28.6941° E ===> 8
#Apollo Bandar	South Mumbai	18.9183748	72.8314429 ==> 46
#London 51.5074° N, -0.1278° W ==> 100
#New York 40.7128° N, 74.0060° W
#South Mumbai Latitude: 18.9600 Longitude: 72.8200 ===> Only 8 !!!!
#Istanbul 41.0082° N, 28.9784° E ==> 100
#29.3759° N, 47.9774° E

neighborhood_latitude = 29.3759
neighborhood_longitude = 47.9774

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    neighborhood_latitude, 
    neighborhood_longitude, 
    radius, 
    LIMIT)
url # display URL

# Send the GET request and examine the resutls

results = requests.get(url).json()
#results
#---------------------------------------------------------------
# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

#----------------------------------------------------------------
#Now we are ready to clean the json and structure it into a pandas dataframe.

venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

print("url:",url)
print("Total Nearby venues:",nearby_venues.shape[0])
nearby_venues.head()
#-----------------------------------------------------------------
nearby_venues_grouped = nearby_venues[['categories','lat']].groupby(['categories']).count().reset_index()
nearby_venues_grouped.rename(columns = {'lat':'count'},inplace = True)
nearby_venues_grouped_sorted = nearby_venues_grouped.sort_values(by= 'count',ascending=False)
print("Unique Categories:",nearby_venues_grouped_sorted.shape[0])
nearby_venues_grouped_sorted.head()

url: https://api.foursquare.com/v2/venues/explore?&client_id=AED1YJAEJO1BSJVJJ5KT2Y2BDGDVPCB21WUXERHTA4B4XXKC&client_secret=5WF0PKUAGWG30ASKZSBV12XHC2IDIQLEHRRPU541XI2JVQCH&v=20180605&ll=29.3759,47.9774&radius=500&limit=200
Total Nearby venues: 46
Unique Categories: 19

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:46: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

                   categories  count
5                        Café     12
6                 Coffee Shop     10
3              Breakfast Spot      3
14  Middle Eastern Restaurant      3
4                Burger Joint      2

In [0]:
#res.reset_index().to_csv("thecsv.csv", orient='records', encoding="utf-8")
nearby_venues.to_csv("kuwait_venues2.csv",encoding="utf-8")
nearby_venues_grouped_sorted.to_csv("kuwait_unique_categories.csv",encoding="utf-8")

####

In [100]:
south_mumbai_venues.head()

  Neighborhood  Neighborhood Latitude  ...  Venue Longitude     Venue Category
0       Colaba              18.915091  ...        72.824151        Men's Store
1       Colaba              18.915091  ...        72.827018  German Restaurant
2       Colaba              18.915091  ...        72.823843                Spa
3       Colaba              18.915091  ...        72.824160        Coffee Shop
4       Colaba              18.915091  ...        72.824119            Brewery

[5 rows x 7 columns]

# **Start Again**

In [0]:
south_mumbai_venues_x1 = south_mumbai_venues.groupby('Neighborhood').count()
south_mumbai_venues_x1.to_csv("south_mumbai_venues_x1_groupby.csv")

In [32]:
### Let's find out how many unique categories can be curated from all the returned venues

print('There are {} uniques categories.'.format(len(south_mumbai_venues['Venue Category'].unique())))
# 104 to 103 to 102  
#120 radius = 90

There are 120 uniques categories.

In [33]:
### 3. Analyze Each Neighborhood

# one hot encoding
south_mumbai_onehot = pd.get_dummies(south_mumbai_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
south_mumbai_onehot['Neighborhood'] = south_mumbai_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [south_mumbai_onehot.columns[-1]] + list(south_mumbai_onehot.columns[:-1])
south_mumbai_onehot = south_mumbai_onehot[fixed_columns]

south_mumbai_onehot.head()

  Neighborhood  American Restaurant  Antique Shop  ...  Wine Bar  Wine Shop  Zoo
0       Colaba                    0             0  ...         0          0    0
1       Colaba                    0             0  ...         0          0    0
2       Colaba                    0             0  ...         0          0    0
3       Colaba                    0             0  ...         0          0    0
4       Colaba                    0             0  ...         0          0    0

[5 rows x 121 columns]

In [34]:
#And let's examine the new dataframe size.
south_mumbai_onehot.shape  # (359, 105) (292,103)

(733, 121)

In [35]:
#Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

south_mumbai_grouped = south_mumbai_onehot.groupby('Neighborhood').mean().reset_index()
south_mumbai_grouped

      Neighborhood  American Restaurant  ...  Wine Shop       Zoo
0    Apollo Bandar             0.000000  ...   0.000000  0.000000
1       Bhuleshwar             0.000000  ...   0.000000  0.000000
2          Byculla             0.000000  ...   0.000000  0.090909
3       Churchgate             0.000000  ...   0.000000  0.000000
4           Colaba             0.000000  ...   0.000000  0.000000
5        Darukhana             0.000000  ...   0.000000  0.000000
6           Dongri             0.000000  ...   0.000000  0.000000
7             Fort             0.000000  ...   0.000000  0.000000
8       Grand Road             0.000000  ...   0.017857  0.000000
9        Kalbadevi             0.026316  ...   0.000000  0.000000
10       Mahalaxmi             0.000000  ...   0.000000  0.000000
11    Malabar Hill             0.000000  ...   0.000000  0.000000
12    Marine Lines             0.000000  ...   0.000000  0.000000
13   Masjid Bandar             0.047619  ...   0.000000  0.000000
14         Mazgaon             0.000000  ...   0.000000  0.000000
15  Mumbai Central             0.000000  ...   0.000000  0.000000
16         Nagpada             0.000000  ...   0.000000  0.000000
17   Nariman Point             0.000000  ...   0.000000  0.000000
18         Pydhoni             0.040000  ...   0.000000  0.000000
19      Walkeshwar             0.000000  ...   0.000000  0.000000
20           Worli             0.000000  ...   0.000000  0.000000

[21 rows x 121 columns]

In [0]:
south_mumbai_grouped.to_csv("south_mumbai_grouped.csv")

In [46]:
south_mumbai_grouped.shape #(21, 105)->(21,103)

(21, 121)

In [36]:
## Let's print each neighborhood along with the top 5 most common venues

num_top_venues = 5

for hood in south_mumbai_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = south_mumbai_grouped[south_mumbai_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Apollo Bandar----
         venue  freq
0         Café  0.11
1        Hotel  0.10
2          Bar  0.06
3  Coffee Shop  0.06
4   Restaurant  0.05


----Bhuleshwar----
                  venue  freq
0             BBQ Joint  0.15
1          Dessert Shop  0.10
2                Market  0.05
3  Fast Food Restaurant  0.05
4                  Food  0.05


----Byculla----
            venue  freq
0     Pizza Place  0.18
1    Dessert Shop  0.18
2  History Museum  0.09
3          Bakery  0.09
4    Cupcake Shop  0.09


----Churchgate----
                  venue  freq
0  Fast Food Restaurant  0.08
1           Coffee Shop  0.08
2                  Café  0.05
3                 Hotel  0.05
4        Cricket Ground  0.05


----Colaba----
         venue  freq
0        Hotel  0.10
1         Café  0.08
2  Coffee Shop  0.08
3          Bar  0.06
4        Diner  0.06


----Darukhana----
                       venue  freq
0           Community Center  0.33
1                       Café  0.33
2                Snack Place  0.33
3  Middle Eastern Restaurant  0.00
4       Other Great Outdoors  0.00


----Dongri----
                venue  freq
0        Dessert Shop  0.12
1  Chinese Restaurant  0.12
2   Convenience Store  0.06
3       Boat or Ferry  0.06
4         Music Venue  0.06


----Fort----
                  venue  freq
0                  Café  0.11
1           Coffee Shop  0.07
2  Fast Food Restaurant  0.07
3                   Bar  0.05
4    Seafood Restaurant  0.05


----Grand Road----
                venue  freq
0                Café  0.09
1         Coffee Shop  0.07
2  Seafood Restaurant  0.05
3                 Bar  0.05
4              Bakery  0.04


----Kalbadevi----
                  venue  freq
0                  Café  0.08
1    Chinese Restaurant  0.05
2                Bakery  0.05
3  Fast Food Restaurant  0.05
4        Ice Cream Shop  0.05


----Mahalaxmi----
                        venue  freq
0                 Coffee Shop  0.19
1                  Restaurant  0.12
2                      Bakery  0.06
3                  Club House  0.06
4  Modern European Restaurant  0.06


----Malabar Hill----
                  venue  freq
0                  Café  0.07
1                  Park  0.07
2          Dessert Shop  0.07
3           Coffee Shop  0.05
4  Fast Food Restaurant  0.05


----Marine Lines----
                 venue  freq
0               Bakery  0.06
1                 Café  0.06
2       Cricket Ground  0.06
3  Indie Movie Theater  0.03
4       Scenic Lookout  0.03


----Masjid Bandar----
               venue  freq
0    Harbor / Marina  0.19
1  Convenience Store  0.10
2              Hotel  0.10
3               Café  0.05
4     Ice Cream Shop  0.05


----Mazgaon----
               venue  freq
0  Convenience Store   0.1
1     Ice Cream Shop   0.1
2         Food Truck   0.1
3        Coffee Shop   0.1
4       Dessert Shop   0.1


----Mumbai Central----
                           venue  freq
0           Fast Food Restaurant  0.17
1               Department Store  0.12
2                     Food Truck  0.08
3  Vegetarian / Vegan Restaurant  0.08
4                 Ice Cream Shop  0.08


----Nagpada----
                  venue  freq
0            Restaurant  0.17
1  Fast Food Restaurant  0.11
2      Department Store  0.11
3          Dessert Shop  0.11
4          Cupcake Shop  0.06


----Nariman Point----
                  venue  freq
0    Italian Restaurant  0.08
1  Fast Food Restaurant  0.07
2                 Hotel  0.07
3           Coffee Shop  0.06
4            Restaurant  0.06


----Pydhoni----
                  venue  freq
0        Ice Cream Shop  0.12
1          Dessert Shop  0.12
2  Fast Food Restaurant  0.08
3             BBQ Joint  0.08
4            Restaurant  0.08


----Walkeshwar----
                  venue  freq
0        Ice Cream Shop  0.11
1            Restaurant  0.08
2                  Café  0.08
3                   Gym  0.05
4  Fast Food Restaurant  0.05


----Worli----
            venue  freq
0            Café  0.18
1  Scenic Lookout  0.18
2          Bakery  0.12
3     Pizza Place  0.06
4      Playground  0.06

In [0]:
#Let's put that into a pandas dataframe
#First, let's write a function to sort the venues in descending orde

def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [38]:
#Now let's create the new dataframe and display the top 10 venues for each neighborhood.

num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = south_mumbai_grouped['Neighborhood']

for ind in np.arange(south_mumbai_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(south_mumbai_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

    Neighborhood  ... 10th Most Common Venue
0  Apollo Bandar  ...                    Spa
1     Bhuleshwar  ...                   Food
2        Byculla  ...      Electronics Store
3     Churchgate  ...     Chinese Restaurant
4         Colaba  ...             Restaurant

[5 rows x 11 columns]

In [0]:
neighborhoods_venues_sorted.to_csv("south_mumbai_top10_venue_categories_minus_indian_rest.csv")

# The second iteration starts from here.

## Increase number of clusters from 5 to 10.

In [0]:
# Run k-means to cluster the neighborhood into 5 clusters.
# Try with more clusters and see results.
# set number of clusters
#kclusters = 5 # First Iteration
#kclusters = 10 # Second Iteration
#kclusters = 5 # Third Iteration after removing Indian restaurants
kclusters = 10 # Fourth Iteration after removing Indian restaurants

In [41]:
# 4. Cluster Neighborhoods
south_mumbai_grouped_clustering = south_mumbai_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(south_mumbai_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([7, 2, 5, 7, 7, 1, 4, 7, 7, 0], dtype=int32)

In [43]:
### Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

ValueError: ignored

In [44]:
### Now merge both dataframes

south_mumbai_merged = south_mumbai_data

# merge two dataframes
south_mumbai_merged = south_mumbai_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

south_mumbai_merged.head() 
# check 'Cluster Labels' column has been added to dataframe

    Neighborhood       Borough  ...  9th Most Common Venue  10th Most Common Venue
0         Colaba  South Mumbai  ...                    Spa              Restaurant
1  Apollo Bandar  South Mumbai  ...                Brewery                     Spa
2           Fort  South Mumbai  ...         Clothing Store          History Museum
3     Churchgate  South Mumbai  ...                    Bar      Chinese Restaurant
4  Nariman Point  South Mumbai  ...         Ice Cream Shop          Sandwich Place

[5 rows x 15 columns]

In [0]:
south_mumbai_merged.to_csv("south_mumbai_cluster_iteration_5_900.csv")

In [45]:
#Finally, let's visualize the resulting clusters
#South Mumbai Latitude: 18.9600 Longitude: 72.8200
latitude  = 18.9600
longitude = 72.8200

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(south_mumbai_merged['Latitude'], south_mumbai_merged['Longitude'], south_mumbai_merged['Neighborhood'], south_mumbai_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

### This concludes the iteration No . Thank You.